### ISSUE TITLE
Don't work CallbackData.unpack

### ISSUE THREAD

**Issue by Oleksandrigo** [aiogram/aiogram#1041]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11

### Python version

3.10

### aiogram version

3.0b5

### Expected behavior

The string from the callback data should be parsed to CallbackData type

### Current behavior

Take error 
```
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\filters\callback_data.py", line 98, in unpack
    prefix, *parts = value.split(cls.__separator__)
AttributeError: type object 'CallbackData' has no attribute '__separator__'
```

### Steps to reproduce

1. Watch code example below
2. 

### Code example

```python3
class SessionMiddleware(BaseMiddleware):
    async def __call__(
            self,
            handler: Callable[[TelegramObject, Dict[str, Any]], Awaitable[Any]],
            event: TelegramObject,
            data: Dict[str, Any]
    ) -> Any:
        if isinstance(event, CallbackQuery):
            print(CallbackData.unpack(event.data)) # <- error here

        await handler(event, data)
```

### Logs

```sh
AttributeError: type object 'CallbackData' has no attribute '__separator__'
Traceback (most recent call last):
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 293, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 142, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 23, in __call__
    return await handler(event, data)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\fsm\middleware.py", line 34, in __call__
    return await handler(event, data)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 111, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 260, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\router.py", line 115, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\router.py", line 124, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\dispatcher\event\telegram.py", line 111, in trigger
    return await wrapped_inner(event, kwargs)
  File "D:\Python_projects\TheTowerGame\middlewares\session_id_middleware.py", line 16, in __call__
    print(CallbackData.unpack(event.data))
  File "D:\Python_projects\TheTowerGame\venv\lib\site-packages\aiogram\filters\callback_data.py", line 98, in unpack
    prefix, *parts = value.split(cls.__separator__)
AttributeError: type object 'CallbackData' has no attribute '__separator__'
```

**Comment by evgfilim1** [comment]
Hello, @Oleksandrigo, and thanks for reporting. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for the issue you're encountering?

**Comment by Oleksandrigo** [comment]
Well, my task is to check all the colbels, and compare the value of a certain field with the value from the storage (MemoryStorage). That's why I tried to use unpack method, because I thought that it will automatically unpack data into some abstract object with necessary fields for checking, instead of doing split(":"). In addition, I can't identify any particular CallbackData class, as there are several, but they all have a session_id field.

**Comment by Oleksandrigo** [comment]
In general, I was able to solve my problem without the `unpack`. I extracted the callback data as `data.get('callback_data')`
