### ISSUE TITLE
Error sending message from thread: Timeout context manager should be used inside a task

### ISSUE THREAD

**Issue by iyamk** [aiogram/aiogram#1083]
### Checklist

- [ ] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Arch linux last

### Python version

3.10.8

### aiogram version

aiogram==3.0.0b6

### Expected behavior

Every 5 seconds should send a message to the admin: Test

### Current behavior

RuntimeError: Timeout context manager should be used inside a task

### Steps to reproduce

1. Fill in bot_token and your telegram userid
2. Run code

### Code example

```python3
from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command
import asyncio
import time
import threading

bot_token = ''
admin_id = ''

bot = Bot(token=bot_token, parse_mode='html')
dp = Dispatcher()

async def send_admin():
    time.sleep(2)
    while True:
        await bot.send_message(admin_id, 'Test')
        time.sleep(5)

@dp.message(Command('start'))
async def send_welcome(message: types.Message):
    await message.answer('Hello')

async def main():
    await dp.start_polling(bot)

def between_callback():
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(send_admin())
    loop.close()

_thread = threading.Thread(target=between_callback)
_thread.start()

if __name__ == "__main__":
    asyncio.run(main())
```

### Logs

```sh
Exception in thread Thread-1 (between_callback):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/bot3/test.py", line 29, in between_callback
    loop.run_until_complete(send_admin())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/bot3/test.py", line 16, in send_admin
    await bot.send_message(admin_id, 'Test')
  File "/home/user/.local/lib/python3.10/site-packages/aiogram/client/bot.py", line 606, in send_message
    return await self(call, request_timeout=request_timeout)
  File "/home/user/.local/lib/python3.10/site-packages/aiogram/client/bot.py", line 364, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/user/.local/lib/python3.10/site-packages/aiogram/client/session/base.py", line 182, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/user/.local/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 149, in make_request
    async with session.post(
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/home/user/.local/lib/python3.10/site-packages/aiohttp/helpers.py", line 700, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
^CTraceback (most recent call last):
  File "/home/user/bot3/test.py", line 36, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1863, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
```

### Additional information

Now can’t write asynchronous code for my task, I need to do it on threads or tell me how to do something like that on async

**Comment by Olegt0rr** [comment]
You should learn more about python and the difference between threads and coroutines.
It's not a bug.
