### ISSUE TITLE
"Task exception was never retrieved" when calling function "bot.send_photo" (I/O operation on closed file)

### ISSUE THREAD

**Issue by rustequal** [aiogram/aiogram#1129]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

CentOS Linux release 7.9.2009

### Python version

3.8.13

### aiogram version

2.25.1

### Expected behavior

Execution of function "bot.send_photo" without errors.

### Current behavior

the "bot.send_photo" function gives an error "Task exception was never retrieved" in 50% of cases

### Steps to reproduce

The error is floating and repeats in 50% of cases.

### Code example

```python3
async def get_user_photo(user):
  photo, log_text = None, f'Member ID:{user.id} profile photo'
  try:
    upp = await bot.get_user_profile_photos(user.id)
    logging.debug('Found %d photos', upp.total_count)
    if upp.total_count > 0:
      file_id = upp.photos[0][0].file_id
      logging.debug('Photo file_id: %s', file_id)
      file = await bot.get_file(file_id)
      logging.debug('Photo path: %s', file.file_path)
      photo = await bot.download_file(file.file_path)
  except exceptions.TelegramAPIError as err:
    log_error(log_text, err)
  except ClientResponseError as err:
    log_error(log_text, err)
  if photo is None:
    log_text += ' is not available'
  else:
    log_text += ' downloaded successfully'
  logging.info(log_text)
  return photo


async def send_message(user, chat_type, title):
  text = get_chat_title(chat_type, title)
  text += get_user_text(user)
  photo = await get_user_photo(user)
  uids = get_enabled_uids()
  for user_id in uids:
    if photo is not None:
      await bot.send_photo(user_id, photo, text)
    else:
      await bot.send_message(user_id, text)
    logging.debug('Message about new member ID:%d sent to user ID:%d',
                  user.id, user_id)
```

### Logs

```sh
2023-02-16 12:31:24,611 - root - INFO - New member in channel "Test": {"user": {"id": 1854593435, "is_bot": false, "first_name": "Example", "username": "dvdstore"}, "status": "member"}
2023-02-16 12:31:24,666 - root - DEBUG - Found 1 photos
2023-02-16 12:31:24,667 - root - DEBUG - Photo file_id: AgACAgIAAxUAAWPt9-zQB19Kxtd2somtnQYVDfQxAAK3tzEbBahwS2qkEc-vyAzpAQADAgADYQADLgQ
2023-02-16 12:31:24,719 - root - DEBUG - Photo path: photos/file_33.jpg
2023-02-16 12:31:24,757 - root - INFO - Member ID:1854593435 profile photo downloaded successfully
2023-02-16 12:31:24,980 - root - DEBUG - Message about new member ID:1854593435 sent to user ID:1134534455
2023-02-16 12:31:24,982 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1547' coro=<Dispatcher._process_polling_updates() done, defined at /opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/dispatcher/dispatcher.py:407> exception=ValueError('I/O operation on closed file.')>
Traceback (most recent call last):
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 306, in process_update
    return await self.chat_member_handlers.notify(update.chat_member)
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/opt/nirn2-bot/mod_inspector.py", line 163, in message_chat_member
    await send_message(new.user, chat_type, cmu.chat.title)
  File "/opt/nirn2-bot/mod_inspector.py", line 138, in send_message
    await bot.send_photo(user_id, photo, text)
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/bot/bot.py", line 565, in send_photo
    result = await self.request(api.Methods.SEND_PHOTO, payload, files)
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/client.py", line 508, in _request
    req = self._request_class(
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/client_reqrep.py", line 313, in __init__
    self.update_body_from_data(data)
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/client_reqrep.py", line 505, in update_body_from_data
    body = body()
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/formdata.py", line 170, in __call__
    return self._gen_form_data()
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/formdata.py", line 163, in _gen_form_data
    self._writer.append_payload(part)
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/multipart.py", line 829, in append_payload
    size = payload.size
  File "/opt/nirn2-bot/telegram/lib64/python3.8/site-packages/aiohttp/payload.py", line 369, in size
    position = self._value.tell()
ValueError: I/O operation on closed file.
```

### Additional information

I also found out through the debugger that the "bot.download_file" function returns an object of the type "io.BytesIO", and not a file. So at first glance, everything should be fine.

**Comment by JrooTJunior** [comment]
This causes in due to you are trying to send file that is already closed, BytesIO object is not a file but is a file-like object with cursor, so, when you download file cursor is on the last position on the buffer, so, when you read from last position - you don't have any data and that means that buffer is finished.

To fix it you should move cursor to start of the buffer - `photo.seek(0)`
