### ISSUE TITLE
Python 3.9 attached to a different loop

### ISSUE THREAD

**Issue by zedzhen** [aiogram/aiogram#1132]
## Context

* Operating System: Windows 10, Ubuntu 20.04
* Python Version: 3.9.5/3.9.13
* aiogram version: 3.0.0b7
* aiohttp version: 3.8.4
* uvloop version (if installed): -

Windows:
on version 3.10.4 and 3.11.1 it works

## Expected Behavior

work correctly

## Current Behavior

causes an error

## Failure Information (for bugs)

```
Traceback (most recent call last):
  File "C:\path\to\program\bot.py", line 13, in <module>
    dp.run_polling(bot)
  File "D:\Programs\Python395\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 553, in run_polling
    return asyncio.run(
  File "D:\Programs\Python395\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Programs\Python395\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Programs\Python395\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 517, in start_polling
    await asyncio.gather(*done)
  File "D:\Programs\Python395\lib\asyncio\locks.py", line 226, in wait
    await fut
RuntimeError: Task <Task pending name='Task-3' coro=<Event.wait() running at D:\Programs\Python395\lib\asyncio\locks.py:226> cb=[_wait.<locals>._on_completion() at D:\Programs\Python395\lib\asyncio\tasks.py:513]> got Future <Future pending> attached to a different loop
```

### Example code
1)
```
from aiogram import Bot, Dispatcher

bot = Bot('***', parse_mode='HTML')
dp = Dispatcher()

if __name__ == '__main__':
    dp.run_polling(bot)

```
2)
```
import asyncio
from aiogram import Bot, Dispatcher

bot = Bot('***', parse_mode='HTML')
dp = Dispatcher()

async def main():
    await db.start_polling(shared.bot)


if __name__ == '__main__':
    asyncio.run(main())

```
**UPD**
but work
```
import asyncio
from aiogram import Bot, Dispatcher

async def main():
    bot = Bot('***', parse_mode='HTML')
    dp = Dispatcher()
    await db.start_polling(shared.bot)


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by JrooTJunior** [comment]
#1162
