### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

### ISSUE THREAD

**Issue by Pizhlo** [aiogram/aiogram#1135]
## Context

* Operating System: Windows 10
* Python Version: 3.11.1 (also on 3.11.2 the same problem)
* aiogram version: 2.25.1
* aiohttp version: 3.8.4

## Expected Behavior

I expected to connect to the Rethinkdb and don't get any errors.

## Current Behavior

I faced the error `AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?`

## Failure Information (for bugs)

I created storage:
`storage = RethinkDBStorage(db=db, table=table user=user, password=password)`
And then passed it to the dispatcher:
`dp = Dispatcher(bot, storage=storage)`

So when I did it and run my program I got the AttribureError.

### Steps to Reproduce

1. Create bot: `bot = Bot(token=API_TOKEN)`
2. Create storage: `storage = RethinkDBStorage(db=db, table=table user=user, password=password)`
3. Pass it to your dispatcher: `dp = Dispatcher(bot, storage=storage)`
4. Start your RethinkDB
5. Run the code: 
```
if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True, on_startup=on_startup, on_shutdown=on_shutdown)
```

### Failure Logs

My traceback:

```
Traceback (most recent call last):
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\controller.py", line 4, in <module>
    from admin import new_users_handlers, register_admin_handlers, unique_users_handlers
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\admin\__init__.py", line 1, in <module>
    from .main import register_admin_handlers
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\admin\main.py", line 5, in <module>
    from bot import dp
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\bot.py", line 6, in <module>
    from aiogram.contrib.fsm_storage.rethinkdb import RethinkDBStorage
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\venv\Lib\site-packages\aiogram\contrib\fsm_storage\rethinkdb.py", line 6, in <module>
    from rethinkdb.asyncio_net.net_asyncio import Connection
  File "C:\Users\pizhlo21\Desktop\Folder\python\tg_bot_reminder\venv\Lib\site-packages\rethinkdb\asyncio_net\net_asyncio.py", line 42, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?

Process finished with exit code 1
```

Do you know how to solve it?

**Comment by Olegt0rr** [comment]
Not related to aiogram.
Downgrade your python version or ask `rethinkdb` to add python 3.11 support
