### ISSUE TITLE
AttributeError: 'Dispatcher' object has no attribute 'callback_query_handler'

### ISSUE THREAD

**Issue by nightadmin** [aiogram/aiogram#1137]
## Context

* Operating System: Windows 11
* Python Version: Python 3.11
* aiogram version: 3.x

## Expected Behavior

Following the documentation (https://docs.aiogram.dev/en/latest/dispatcher/index.html), 
```python
dp = Dispatcher()
@dp.callback_query_handler(lambda callback_query: True)
async def some_callback_handler(callback_query: types.CallbackQuery):
    ...
```
## Current Behavior

```sh
Traceback (most recent call last):
  File "c:\Users\Mark\Desktop\d\main.py", line 60, in <module>
    @dp.callback_query_handler(lambda callback_query: True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dispatcher' object has no attribute 'callback_query_handler'
```
## Failure Information (for bugs)
Dispatcher object in 3.x aiogram version do not support callback query handlers at all.
The official documentation (see the link) is unfulfilled: some sections still have "Coming soon" in the description.

### Steps to Reproduce

1. Use aiogram 3.x
2. Start this code:
```python
import asyncio
import logging
from aiogram import Bot, Dispatcher, Router, types
from aiogram.filters import Command
from aiogram.types import Message
from aiogram.types import ReplyKeyboardRemove, \
    ReplyKeyboardMarkup, KeyboardButton, \
    InlineKeyboardMarkup, InlineKeyboardButton

# All handlers should be attached to the Router (or Dispatcher)
router = Router()
# Dispatcher is a root router
dp = Dispatcher()
# ... and all other routers should be attached to Dispatcher
dp.include_router(router)

# Initialize Bot instance with a default parse mode which will be passed to all API calls
bot = Bot(TOKEN, parse_mode="HTML")

@router.message(Command(commands=["start"]))
async def command_start_handler(message: Message) -> None:
    """
    This handler receive messages with `/start` command
    """
    if message.chat.type != "private":
        return
    button_hi = InlineKeyboardButton('Next', callback_data="intro_passed")
    greet_kb = InlineKeyboardMarkup()
    greet_kb.add(button_hi)
    await message.answer(f"Test message. Tap Next.", reply_markup=greet_kb)


@dp.callback_query_handler(func=lambda c: c.data == 'intro_passed')
async def process_callback_button1(callback_query: types.CallbackQuery):
    await bot.answer_callback_query(callback_query.id)
    await bot.send_message(callback_query.from_user.id, 'Well done!')

async def main() -> None:
    await dp.start_polling(bot)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
```

### Failure Logs
```sh
Traceback (most recent call last):
  File "c:\Users\Mark\Desktop\d\main.py", line 60, in <module>
    @dp.callback_query_handler(func=lambda c: c.data == 'intro_passed')
     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Dispatcher' object has no attribute 'callback_query_handler'
```

**Comment by JrooTJunior** [comment]
You are reading documentation for 2.x version but have 3.x installed:
2.x: https://docs.aiogram.dev/en/dev-3.x/
3.x https://docs.aiogram.dev/en/latest/

In that case you should read this page: https://docs.aiogram.dev/en/dev-3.x/dispatcher/router.html#callback-query

Note that the `_handler` suffix has been removed from all event handlers
