### ISSUE TITLE
Error with handling message with "_" in text

### ISSUE THREAD

**Issue by 06ED** [aiogram/aiogram#1187]
# Example message text: text_text 
# Full error
```python
Task exception was never retrieved
future: <Task finished name='Task-113' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=CantParseEntities("Can't parse entities: can't find end of the entity starting at byte offset 87")>
Traceback (most recent call last):
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\main.py", line 244, in group_message_handler
    await message.answer(f"🟢 Пост от пользователя {username}\n\n" + new_message, parse_mode="Markdown")
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\types\message.py", line 438, in answer
    return await self.bot.send_message(
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\bot\bot.py", line 346, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\bot\base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "C:\Users\Artyom\PycharmProjects\filterStopPost\venv\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.CantParseEntities: Can't parse entities: can't find end of the entity starting at byte offset 87
```
help please

**Comment by Desiders** [comment]
Ask it here: https://t.me/aiogram (en), https://t.me/aiogram_ru (ru). 

You haven't closed the tag somewhere
