### ISSUE TITLE
Bug/Help needed when sending logs to a Telegram channel

### ISSUE THREAD

**Issue by belgianrubs** [aiogram/aiogram#1193]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 22.04.2 LTS 
* Python Version: Python 3.10.6
* aiogram version: 2.25.1
* aiohttp version: 3.8.4
* uvloop version (if installed): /

## Expected Behavior

I want to send all the error logs to a Telegram channel. The current code I wrote is attached below. Is there something I am missing/doing wrong? 

## Current Behavior

From time to time (not at a specific point, but randomly), I get the errors that are listed below. Although everything seems to be working fine (logs are still send). 

## Failure Information (for bugs)

Could someone give me some pointers on how to avoid these errors? Thanks in advance!

### Steps to Reproduce

```
import asyncio
import logging
import aiogram

# Handles all the error logs that need to be sent to a Telegram channel.
class TelegramHandler(logging.Handler):
    def __init__(self, token, chat_id, level):
        super().__init__(level=level)
        self.token = token
        self.chat_id = chat_id
        self.bot = aiogram.Bot(token)
        self.dispatcher = aiogram.Dispatcher(self.bot)
        self.loop = asyncio.get_event_loop()
        self.logger = logging.getLogger("telegramHandler.py")

    async def send_telegram_message(self, log_entry):
        try:
            await self.bot.send_message(chat_id=self.chat_id, text=log_entry)
        except aiogram.utils.exceptions.BotBlocked:
            self.logger.error("TelegramHandler: Bot was blocked by the user "+str(self.chat_id))
        except aiogram.utils.exceptions.ChatNotFound:
            self.logger.error("TelegramHandler: Chat not found for ID "+str(self.chat_id))
        except aiogram.utils.exceptions.RetryAfter as e:
            self.logger.error("TelegramHandler: Retry after "+str(e.timeout)+" seconds.")
            await asyncio.sleep(e.timeout)
            await self.send_telegram_message(log_entry)
        except aiogram.utils.exceptions.TelegramAPIError:
            self.logger.error("TelegramHandler: Error occurred while sending the message.")
        except RuntimeError:
            self.logger.error("RuntimeError occured.")

    def send_telegram_message_sync(self, log_entry):
        asyncio.run(self.send_telegram_message(log_entry))

    def emit(self, record):
        log_entry = self.format(record)
        self.send_telegram_message_sync(log_entry)
```

### Failure Logs
```
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f6ea4f0a620>
transport: <_SelectorSocketTransport closing fd=17>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 916, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 922, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 717, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 729, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f6ea4f0b490>
transport: <_SelectorSocketTransport closing fd=18>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 916, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 922, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 717, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 729, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 750, in call_soon
    self._check_closed()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by JrooTJunior** [comment]
You can't use async bot to send logs from sync loggers.

If you want to do it - you will need to use queue and put log records into it and thed read this queue from async worker that sends messages into telegram.
