### ISSUE TITLE
Telegram server says Request timeout error

### ISSUE THREAD

**Issue by morington** [aiogram/aiogram#1198]
## Context

* Operating System:
Linux notebook 6.1.31-2-MANJARO
* Python Version:
Python 3.11.3
* aiogram version:
aiogram==3.0.0b7
* aiohttp version:
aiohttp==3.8.4

## Expected Behavior

When starting the bot via dp.start_polling , the telegram bot should start or issue an error message in the code.

## Current Behavior

When starting the bot via dp.start_polling , I get the following error:

raise TelegramNetworkError(method=method, message="Request timeout error")
aiogram.exceptions.TelegramNetworkError: Telegram server says Request timeout error

I am receiving this message for the first time. The browser and python correctly process the site api.telegram.org. I have access to the Internet. All sites work without restrictions.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create a bot.
Minimum code:
```
import logging
import asyncio
from aiogram import Bot, Dispatcher

logger = logging.getLogger(__name__)


async def main():
    # -> Logging
    logging.basicConfig(
        # filename=".bot.log",
        format='[%(asctime)s] [%(name)s] [%(levelname)s] > %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S',
        level=logging.DEBUG,
    )
    logger.debug("-> Bot online")

    # -> Create bot
    bot = Bot(token='YOUT TOKEN')
    dp = Dispatcher()

    await dp.start_polling(bot, allowed_updates=dp.resolve_used_update_types())


if __name__ == '__main__':
    try: asyncio.run(main())
    except (KeyboardInterrupt, SystemError):
        print('-> Bot stopped!')
```
2. Run.
3. Get an error (I asked others, everything works fine, I also tried to recreate the bot in telegram)

[2023-06-25 19:57:53] [__main__] [DEBUG] > -> Bot online
[2023-06-25 19:57:53] [aiogram.dispatcher] [INFO] > Start polling
[2023-06-25 19:58:54] [aiogram.dispatcher] [INFO] > Polling stopped
Traceback (most recent call last):
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py", line 153, in make_request
    async with session.post(
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/morington/projects/portfolio/test_bot/main.py", line 35, in <module>
    try: asyncio.run(main())
         ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/morington/projects/portfolio/test_bot/main.py", line 31, in main
    await dp.start_polling(bot, allowed_updates=dp.resolve_used_update_types())
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 517, in start_polling
    await asyncio.gather(*done)
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 328, in _polling
    user: User = await bot.me()
                 ^^^^^^^^^^^^^^
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/client/bot.py", line 246, in me
    self._me = await self.get_me()
               ^^^^^^^^^^^^^^^^^^^
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/client/bot.py", line 1652, in get_me
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/client/bot.py", line 374, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/client/session/base.py", line 194, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/morington/projects/portfolio/test_bot/venv/lib/python3.11/site-packages/aiogram/client/session/aiohttp.py", line 158, in make_request
    raise TelegramNetworkError(method=method, message="Request timeout error")
aiogram.exceptions.TelegramNetworkError: Telegram server says Request timeout error

**Comment by morington** [comment]
The problem was with the ISP. Sorry for the topic.

**Comment by SeventhFret** [comment]
@morington, what was the exact problem? Because I have similar problem and bot doesn't respond to any messages

```
    raise TelegramNetworkError(method=method, message="Request timeout error")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - Request timeout error

```

**Comment by morington** [comment]
> @morington, what was the exact problem? Because I have similar problem and bot doesn't respond to any messages
> 
> ```
>     raise TelegramNetworkError(method=method, message="Request timeout error")
> aiogram.exceptions.TelegramNetworkError: HTTP Client says - Request timeout error
> 
> ```

Hi!
I dealt with this problem.  It was with my ISP.  He gave out a strange IP address that interfered with requests to the telegram servers.  I check this fact through package managers or pip.  If they load late or take a long time, it's definitely the provider's fault.

**Comment by OOOOEEES** [comment]
Здравствуйте! Можете поподробнее рассказать как решили проблему? Провайдер на какое-то время исправил ошибку (минут 10 от силы), но в последствии все повторилось. Прошу вас

**Comment by morington** [comment]
> Здравствуйте! Можете поподробнее рассказать как решили проблему? Провайдер на какое-то время исправил ошибку (минут 10 от силы), но в последствии все повторилось. Прошу вас

Приветствую! Пробуй менять IP адреса. В течении около 10-15 минут достаточно отключить интернет.

**Comment by Olegt0rr** [comment]
@OOOOEEES @morington please, respect others - use english here.
