### ISSUE TITLE
Cause exception while getting updates [asyncio.TimeoutError from None]

### ISSUE THREAD

**Issue by GooDeeJAY** [aiogram/aiogram#1209]
## Context

* Operating System: Ubuntu 22.04 (WSL 2)
* Python Version: 3.10
* aiogram version: 2.25.1
* aiohttp version: 3.8.4

## Expected Behavior

Working without any TimeoutError exceptions

## Current Behavior

Getting `asyncio.exceptions.TimeoutError` exceptions occasionally during the polling process

## Failure Information (for bugs)

```console
Cause exception while getting updates.                                                                                           
Traceback (most recent call last):                                                                                               
  File "/home/.../venv/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(                                                                                        
  File "/home/.../venv/lib/python3.10/site-packages/aiogram/bot/bot.py", line 110, in get_updates                
    result = await self.request(api.Methods.GET_UPDATES, payload)                                                                
  File "/home/.../venv/lib/python3.10/site-packages/aiogram/bot/base.py", line 236, in request                   
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,                      
  File "/home/.../venv/lib/python3.10/site-packages/aiogram/bot/api.py", line 139, in make_request               
    async with session.post(url, data=req, **kwargs) as response:                                                                
  File "/home/.../venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__                 
    self._resp = await self._coro                                                                                                
  File "/home/.../venv/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request                    
    with timer:                                                                                                                  
  File "/home/.../venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__                   
    raise asyncio.TimeoutError from None                                                                                         
asyncio.exceptions.TimeoutError 
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Start the script
2. Start using the bot, by sending commands/texts
3. Occasionally get these TimeoutError messages in console

### Code fragment:
```python3
async def main():
    bot = Bot(token=config.BOT_TOKEN, validate_token=True, parse_mode=ParseMode.HTML, timeout=2)
    dp = Dispatcher(bot)
    await dp.skip_updates()
    await dp.start_polling(fast=False)

if __name__ == '__main__':
    asyncio.run(main())
```

Is this an issue related with Telegram Bot API servers? Or its from my ISP side? Or is it from the under hood polling implementation of the aiogram

**Comment by JrooTJunior** [comment]
This issue is not related with aiogram directly, but check your internet connection, DNS servers configuration and also increase timeout for bot.
