### ISSUE TITLE
Importing a Bot class raises a TypeError exception

### ISSUE THREAD

**Issue by ivankarmanow** [aiogram/aiogram#1222]
## Context

Importing a Bot class raises a TypeError exception

* Operating System: Windows 11
* Python Version: 3.10
* aiogram version: 3.0.0b8
* aiohttp version: 3.8.4
* Pydantic version: 2.0

## Expected Behavior

Correct import of Bot from aiogram

## Current Behavior

Importing Bot class from aiogram raises `TypeError exception: ForwardRef.__init__() got an unexpected keyword argument 'is_class'`
Code:
`from aiogram import Bot`
Full Exception Message:
```
Traceback (most recent call last):
  File "c:\Users\user\Co\Work\bot\mre.py", line 1, in <module>
    from aiogram import Bot
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\aiogram\__init__.py", line 5, in <module>
    from . import enums, methods, types
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\aiogram\methods\__init__.py", line 1, in <module>
    from .add_sticker_to_set import AddStickerToSet
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\aiogram\methods\add_sticker_to_set.py", line 3, in <module>
    from ..types import InputSticker
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\aiogram\types\__init__.py", line 3, in <module>
    from .animation import Animation
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\aiogram\types\animation.py", line 11, in <module>
    class Animation(TelegramObject):
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 171, in __new__
    set_model_fields(cls, bases, config_wrapper, types_namespace)
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\pydantic\_internal\_model_construction.py", line 361, in set_model_fields
    fields, class_vars = collect_model_fields(cls, bases, config_wrapper, types_namespace, typevars_map=typevars_map)
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\pydantic\_internal\_fields.py", line 96, in collect_model_fields
    type_hints = get_cls_type_hints_lenient(cls, types_namespace)
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 212, in get_cls_type_hints_lenient
    hints[name] = eval_type_lenient(value, globalns, localns)
  File "C:\Users\user\Co\Work\bot\.venv\lib\site-packages\pydantic\_internal\_typing_extra.py", line 221, in eval_type_lenient
    value = _make_forward_ref(value, is_argument=False, is_class=True)
TypeError: ForwardRef.__init__() got an unexpected keyword argument 'is_class'
```

### Steps to Reproduce

1. Create a virtual environment with Python 3.10 and aiogram 3.0.0b8
2. Launch that code `from aiogram import Bot`
3. Catch the exception

**Comment by Olegt0rr** [comment]
Can't reproduce on macOS with python 3.10, 3.11

My pip freeze

```
aiofiles==23.1.0
aiogram==3.0.0b8
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.2.0
frozenlist==1.4.0
idna==3.4
Jinja2==3.1.2
jsonschema==4.18.4
jsonschema-specifications==2023.7.1
magic-filter==1.0.10
MarkupSafe==2.1.3
multidict==6.0.4
pydantic==2.0.3
pydantic_core==2.3.0
PyYAML==5.2b1
referencing==0.30.0
requests==2.31.0
rpds-py==0.9.2
swagger-parser==1.0.2
swagger-spec-validator==3.0.3
typing_extensions==4.7.1
urllib3==2.0.4
yarl==1.9.2

```

**Comment by Olegt0rr** [comment]
@ivankarmanow , please, provide more info about your pydantic versions

**Comment by ivankarmanow** [comment]
@Olegt0rr, I updated Python to version 3.10.11 and the problem disappeared. However, on Python version 3.10.0 the problem persists. Here is my pip freeze:
```
aiofiles==23.1.0
aiogram==3.0.0b8
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
async-timeout==4.0.2
attrs==23.1.0
certifi==2023.5.7
charset-normalizer==3.2.0
frozenlist==1.4.0
idna==3.4
magic-filter==1.0.10
multidict==6.0.4
pydantic==2.0.3
pydantic_core==2.3.0
typing_extensions==4.7.1
yarl==1.9.2
```

**Comment by Olegt0rr** [comment]
I'm glad you were able to resolve the issue. 
I'm also glad the problem isn't on our side.

I will close your issue. It will still show up in search for those who run into a similar problem. 
The recommendation would be to update the Python version.

Thank you!
