### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by MrArlian** [aiogram/aiogram#1224]
## Context

* Operating System: Fedora Linux 38
* Python Version: 3.10.9
* aiogram version: 2.25.1
* aiohttp version: 3.8.3

## Expected Behavior

No traceback, just the function normal return value.

## Current Behavior

```python
Traceback (most recent call last):
  File "E:\Python\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "E:\Python\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "E:\Python\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "E:\Python\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "E:\Python\lib\site-packages\aiogram\dispatcher\handler.py", line 108, in notify
    data.update(await check_filters(handler_obj.filters, args))
  File "E:\Python\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 77, in check_filters
    f = await execute_filter(filter_, args)
  File "E:\Python\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 61, in execute_filter
    return await filter_.filter(*args, **filter_.kwargs)
  File "E:\Python\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 166, in __call__
    return await self.check(*args)
  File "E:\Python\lib\site-packages\aiogram\utils\callback_data.py", line 121, in check
    data = self.factory.parse(query.data)
  File "E:\Python\lib\site-packages\aiogram\utils\callback_data.py", line 86, in parse
    prefix, *parts = callback_data.split(self.sep)
AttributeError: 'NoneType' object has no attribute 'split'
```

### Steps to Reproduce

When attempting to press the "CallbackGame" button, Telegram sends empty callback data. I use the "CallbackDataFilter" in almost all handlers.

Actually, this can be fixed by doing the following:

file: /aiogram/utils/callback_data.py : line 121
```python
    async def check(self, query: types.CallbackQuery):
        try:
            data = self.factory.parse(query.data)
        except ValueError:
            return False
```
```python
    async def check(self, query: types.CallbackQuery):
        try:
            data = self.factory.parse(query.data or '')
        except ValueError:
            return False
```

**Comment by JrooTJunior** [comment]
But confirmed.

Feel free to contribute to `aiogram`, you can fix it and create pull-request with this fix.

(https://t.me/aiogram_live/90)
