### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'values'

### ISSUE THREAD

**Issue by erLCoder** [aiogram/aiogram#1225]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 11 22H2
* Python Version: 3.11.4
* aiogram version: 2.25.1
* aiohttp version: 3.8.4
* uvloop version (if installed): I`m not using it

## Expected Behavior

I wanted to split my code in 2 files. I have main.py where my bot initializes and running asyncio.run(dp.start_polling()). Then I have funcs.py where I created 4 classes(Client, Client_callbacks, Admin, Admin_callbacks)
I`m trying to call a function something like this:

main.py
```
bot = Bot(token=token)
dp = Dispatcher(bot, storage=MemoryStorage())
p2p = QiwiP2P(auth_key=payment_token)

@dp.message_handler(lambda message: message.text == 'Профиль') # profile_menu
async def profile_menu(message: Message, state: FSMContext):
    await Client.profile_menu(message=Message, state=FSMContext, bot=bot)

if __name__ == "__main__":
    # Start polling loop
    asyncio.run(dp.start_polling())
```

funcs.py
```
class Client():
  @staticmethod
      async def profile_menu(message: Message, state: FSMContext, bot):
          chat_id = message.chat.id
          row = await Database.get_user_data(chat_id=chat_id)
          login = row['login'] if row else None
          password = row['password'] if row else None
          hwid = row['hwid'] if row else None
          expiration_date = row['expiration_date'] if row else None
          user = await bot.get_chat(chat_id)
          username = user.username if user.username else 'Unknown user'
  
          if not await Database.check_chat_id(chat_id=chat_id):
              await message.answer('Вы еще не зарегистрированы!')
              logging.info(f'Попытка открытия профиля незареганного пользователя @{username}, id: {chat_id}')
              await Client.ask_login(message, state)
              return
  
          logging.info(f'Пользователь заходит в профиль @{username}, id: {chat_id}')
  
          if await Database.check_sub_user(chat_id=chat_id):
              pass
          else:
              expiration_date = 'Нет активной подписки!'
  
          if await Database.get_hwid_user(chat_id=chat_id) == None:
              hwid = 'HWID не записан! Запустите чит-клиент'
  
          await message.answer(
              f'''
          Ваш логин: {login}
      Ваш пароль: {password}
      Ваш HWID: {hwid}
      Дата окончания подписки: {expiration_date}
          ''',
              reply_markup=keyboards.profile_keyboard
          )
  
  
          await state.finish()
```

## Current Behavior

When I`m running main.py and clicking button which handling by def profile_menu. My console throw me an exception. 

`AttributeError: 'NoneType' object has no attribute 'values'`

### Steps to Reproduce

1. Run main.py
2. Click button "profile menu" in telegram
3. I get it

### Failure Logs

```
2023-07-25 12:50:59,236 - aiogram.dispatcher.dispatcher - INFO - Start polling.
2023-07-25 12:50:59,565 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-5' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=AttributeError("'NoneType' object has no attribute 'values'")>
Traceback (most recent call last):
  File "C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Max\Desktop\Разработка\project\diveyareg_bot\main.py", line 53, in profile_menu
    await Client.profile_menu(message=Message, state=FSMContext, bot=bot)
  File "E:\Max\Desktop\Разработка\project\diveyareg_bot\funcs.py", line 98, in profile_menu
    chat_id = message.chat.id
              ^^^^^^^^^^^^
  File "C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\types\fields.py", line 69, in __get__
    return self.get_value(instance)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\demki\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiogram\types\fields.py", line 46, in get_value
    return instance.values.get(self.alias, self.default)
           ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by erLCoder** [comment]
## Explanation
I fixed it, I had given for args like this

```
@dp.message_handler(lambda message: message.text == 'Профиль') # profile_menu
async def profile_menu(message: Message, state: FSMContext):
    await Client.profile_menu(message=Message, state=FSMContext, bot=bot)
```
but it`s wrong way

## Reason
Message and FSMContext are classes thats why I had that issue. If u encounter with this issue u have to give variables like:

## Way to fix
`await Client.profile_menu(message, state)`

**Comment by GalllaxyCode** [comment]
Ну ты и баклажан как до такого додуматься можно
