### ISSUE TITLE
webhook cannot process callback request

### ISSUE THREAD

**Issue by Delitel-WEB** [aiogram/aiogram#1270]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Arch Linux x86_64

### Python version

3.11.3

### aiogram version

2.25.1

### Expected behavior

the bot must respond to the callback buttons

### Current behavior

Диспетчер не может управлять состоянием

```
Error handling request
Traceback (most recent call last):
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/main.py", line 29, in handle_webhook
    await dp.process_update(update)
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/bot/commands/get_films.py", line 27, in get_films
    await SelectFilms.select_film.set()
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiogram/dispatcher/filters/state.py", line 56, in set
    state = Dispatcher.get_current().current_state()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'current_state'
```

### Steps to reproduce

Installing a web hack leads to this behavior
long_polling does not result in this error

### Code example

```python3
main.py

from bot.core import dp, Bot
import bot.commands
from aiohttp import web
from bot.cfg import botToken
from aiogram.types import Update
from aiogram import Bot as bt

app = web.Application()
bt.set_current(Bot)

webhook_path = f"/{botToken}"


async def on_startup(_):
    await set_webhook()


async def set_webhook():
    url = f"https://9a6c-82-209-118-14.ngrok.io{webhook_path}"
    await Bot.set_webhook(url)


async def handle_webhook(request):
    url = str(request.url)
    index = url.rfind("/")
    token = url[index + 1 :]
    if botToken == token:
        request_data = await request.json()
        update = Update(**request_data)
        await dp.process_update(update)
        return web.Response()
    else:
        return web.Response(status=403)


app.router.add_post(webhook_path, handle_webhook)


if __name__ == "__main__":
    app.on_startup.append(on_startup)
    web.run_app(app, host="0.0.0.0", port=8081)



bot/core/__init__.py
```python
from ..cfg import botToken
from aiogram import Bot, Dispatcher
from aiogram.contrib.fsm_storage.memory import MemoryStorage


Bot = Bot(botToken)
storage = MemoryStorage()
dp = Dispatcher(Bot, storage=storage)


```
```


### Logs

```sh
Error handling request
Traceback (most recent call last):
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/main.py", line 29, in handle_webhook
    await dp.process_update(update)
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 283, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/delitel/Документы/projects/py/telegramFilms/bot/commands/get_films.py", line 27, in get_films
    await SelectFilms.select_film.set()
  File "/home/delitel/Документы/projects/py/telegramFilms/env/lib/python3.11/site-packages/aiogram/dispatcher/filters/state.py", line 56, in set
    state = Dispatcher.get_current().current_state()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'current_state'

```
```


### Additional information

_No response_

**Comment by Delitel-WEB** [comment]
This error occurs in principle wherever FSM is used
