### ISSUE TITLE
Aiogram starts and stops polling with TimeoutError

### ISSUE THREAD

**Issue by keneshindev** [aiogram/aiogram#1394]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu 22.04.2 LTS

### Python version

3.10.12

### aiogram version

3.3.0

### Expected behavior

The bot starts polling successfully and doesn't shutdown

### Current behavior

The bot starts polling and after about 30-60 seconds stops and reports the TimeoutError

### Steps to reproduce

1. init the virtualenv and install everything
2. run the code (pretty sure it's a one of a kind error)

### Code example

```python3
import logging
from asyncio import run
from aiogram import Bot, Dispatcher
logging.basicConfig(level=logging.INFO)
token = 'token here'
bot = Bot(token)
async def main():
    dp = Dispatcher()
    await dp.start_polling(bot)

run(main())
```

### Logs

```sh
(neurobot) root@vdska:~/neurobot# python3 main2.py
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Polling stopped
Traceback (most recent call last):
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 171, in make_request
    async with session.post(
  File "/root/neurobot/lib/python3.10/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
  File "/root/neurobot/lib/python3.10/site-packages/aiohttp/client.py", line 500, in _request
    with timer:
  File "/root/neurobot/lib/python3.10/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/neurobot/main2.py", line 11, in <module>
    run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/neurobot/main2.py", line 9, in main
    await dp.start_polling(bot)
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 551, in start_polling
    await asyncio.gather(*done)
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 340, in _polling
    user: User = await bot.me()
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/client/bot.py", line 313, in me
    self._me = await self.get_me()
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/client/bot.py", line 1770, in get_me
    return await self(call, request_timeout=request_timeout)
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/client/bot.py", line 441, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/client/session/base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/root/neurobot/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 176, in make_request
    raise TelegramNetworkError(method=method, message="Request timeout error")
aiogram.exceptions.TelegramNetworkError: HTTP Client says - Request timeout error
```

### Additional information

I can get anything from Telegram API freely (getMe/getUpdates methods) and it doesn't take me long enough
This issue also only persists on my host in Netherlands, it works locally and I can't get to reproduce it locally
Everything works with any other lib but aiogram doesn't work
If it helps, I'm using aiohttp 3.9.1

**Comment by Olegt0rr** [comment]
It's a network issue with your hoster, try to use another server or another hoster

**Comment by keneshindev** [comment]
As I previously said, it's not a network issue, I can fetch Telegram Bot API just fine and any other lib also works just fine
Yes, I did solve it the easy way by changing the server but that doesn't fix the cause of problem itself

**Comment by JrooTJunior** [comment]
Do you have IPv6 enabled?

**Comment by keneshindev** [comment]
I think I do, my host has global IPv6 assigned
But it works on my other host which has IPv6 too
Disabling IPv6 confirmed that it works without it, so I think this issue is now resolved?

**Comment by JrooTJunior** [comment]
Bot API has well-known issues with accessing via IPv6, so, it is recommended to disable it and prefer to use IPv4 with bots.

**Comment by RickCastle2018** [comment]
@ghost could you give any instructions on how to make those settings to fix the issue?

**Comment by Coderik** [comment]
Having the same issue. Polling times out after about a minute on default settings.

```
2025-01-31 18:08:01,194 - aiogram.dispatcher - INFO - Start polling
2025-01-31 18:09:02,003 - aiogram.dispatcher - INFO - Polling stopped
Traceback (most recent call last):                                                                                                       
  File ".../.venv/lib/python3.10/site-packages/aiohttp/client.py", line 703, in _request                  
    conn = await self._connector.connect(                                                                                                
  File ".../.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 548, in connect                
    proto = await self._create_connection(req, traces, timeout)                                                                          
  File ".../.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1056, in _create_connection    
    _, proto = await self._create_direct_connection(req, traces, timeout)                                                                
  File ".../.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1369, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(                                                                                  
  File ".../.venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1115, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(                                                                                      
  File ".../.venv/lib/python3.10/site-packages/aiohappyeyeballs/impl.py", line 89, in start_connection    
    sock, _, _ = await _staggered.staggered_race(                                                                                        
  File ".../.venv/lib/python3.10/site-packages/aiohappyeyeballs/_staggered.py", line 160, in staggered_race
    done = await _wait_one(                                                                                                              
  File ".../.venv/lib/python3.10/site-packages/aiohappyeyeballs/_staggered.py", line 41, in _wait_one     
    return await wait_next                                                                                                               
asyncio.exceptions.CancelledError                                                                                                        
                                                                                                                                         
The above exception was the direct cause of the following exception:                                                                     
                                                                                                                                         
Traceback (most recent call last):                                                                                                       
  File ".../.venv/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 181, in make_request
    async with session.post(                                        
  File ".../.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1425, in __aenter__               
    self._resp: _RetType = await self._coro
  File ".../.venv/lib/python3.10/site-packages/aiohttp/client.py", line 607, in _request
    with timer:                                                                                                                          
  File ".../.venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 671, in __exit__
    raise asyncio.TimeoutError from exc_val                                                                                              
asyncio.exceptions.TimeoutError
```
