### ISSUE TITLE
FSM Redis connectivity: AttributeError: 'NoneType' object has no attribute '_add_writer'

### ISSUE THREAD

**Issue by leshchenko1979** [aiogram/aiogram#1618]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Latest Ubuntu

### Python version

3.13.1

### aiogram version

latest

### Expected behavior

Bot should update FSM state.

### Current behavior

It periodically fails to do so.

### Steps to reproduce

It seems like the reason is a flaky redis connection.

### Logs

```sh
Traceback (most recent call last):
  File "/bot.py", line 49, in handle_incoming_request
    await asyncio.wait_for(
    ...<2 lines>...
    )
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiogram/dispatcher/dispatcher.py", line 189, in feed_raw_update
    return await self._feed_webhook_update(bot=bot, update=parsed_update, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiogram/dispatcher/dispatcher.py", line 368, in _feed_webhook_update
    return await self.feed_update(bot, update, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 56, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    data.update({"state": context, "raw_state": await context.get_state()})
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiogram/fsm/context.py", line 15, in get_state
    return await self.storage.get_state(key=self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiogram/fsm/storage/redis.py", line 98, in get_state
    value = await self.redis.get(redis_key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/redis/asyncio/client.py", line 616, in execute_command
    return await conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/redis/asyncio/client.py", line 589, in _send_command_parse_response
    await conn.send_command(*args)
  File "/usr/local/lib/python3.13/site-packages/redis/asyncio/connection.py", line 505, in send_command
    await self.send_packed_command(
        self.pack_command(*args), check_health=kwargs.get("check_health", True)
    )
  File "/usr/local/lib/python3.13/site-packages/redis/asyncio/connection.py", line 480, in send_packed_command
    self._writer.writelines(command)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 343, in writelines
    self._transport.writelines(data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 1177, in writelines
    self._loop._add_writer(self._sock_fd, self._write_ready)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_add_writer'
```

### Additional information

The webhook processor that's using aiogram runs within a serverless container within Yandex Cloud with 20% of CPU.

**Comment by Olegt0rr** [comment]
Look at the traceback... It's not an aiogram bug. 

First of all, try to figure out how do you creating object to make loop as `None` (maybe it was initiated before loop?)
If all required objects created after loop, try to create an issue for redis
