### ISSUE TITLE
Payments example fails

### ISSUE THREAD

**Issue by kamikaze** [aiogram/aiogram#189]
By using following example: https://aiogram.readthedocs.io/en/latest/examples/payments.html
I'm getting:
```
Traceback (most recent call last):
  File "smart_guru_bot.py", line 46, in <module>
    async def shipping(shipping_query: types.ShippingQuery):
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 765, in decorator
    self.register_shipping_query_handler(callback, *custom_filters, state=state, run_task=run_task, **kwargs)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 744, in register_shipping_query_handler
    **kwargs)
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/dispatcher/filters/factory.py", line 53, in resolve
    {k: v for k, v in full_config.items() if v is not None}))
  File "/home/kamikaze/.venv37/lib/python3.7/site-packages/aiogram/dispatcher/filters/factory.py", line 73, in _resolve_registered
    raise NameError('Invalid filter name(s): \'' + '\', '.join(full_config.keys()) + '\'')
NameError: Invalid filter name(s): 'func'
```

As I see it is being related to:

```python
@dp.shipping_query_handler(func=lambda query: True)
```
and
```python
@dp.pre_checkout_query_handler(func=lambda query: True)
```

**Comment by JrooTJunior** [comment]
That's because `func` filter is removed few versions ago but this example is not updated.

**Comment by Birdi7** [comment]
It's fixed [here](https://github.com/aiogram/aiogram/commit/68aa7dbf1a72dce7df87b22c227224efb558c7ad) actually and is merged in the dev-2.x

**Comment by JrooTJunior** [comment]
Fixed
