### ISSUE TITLE
CantParseEntities exception for message with single _ or * and markdown parse mode

### ISSUE THREAD

**Issue by delimitry** [aiogram/aiogram#197]
## Context

* Operating System: Ubuntu 18.04
* Python Version: 3.7.4
* aiogram version: 2.3
* aiohttp version: 3.5.4

## Expected Behavior

Handle such cases and escape symbols `_`, `*` and replace with `\_` and `\*` correspondingly.
Or raise exception with more clear message.

## Current Behavior

Fails with exception: `aiogram.utils.exceptions.CantParseEntities: Can't parse entities: can't find end of the entity starting at byte offset ...`

## Failure Information (for bugs)

`CantParseEntities` exception raises for message with single `_` or `*` and `MARKDOWN` parse mode due to unclosed underscore or asterisk "tag".

### Steps to Reproduce

To reproduce send reply message with single `_` or `*` and `parse_mode=ParseMode.MARKDOWN`:
```
@dp.message_handler(commands=['start', 'help'])
async def cmd_handler(message: types.Message):
    text = 'some_text - description\n'
    await message.reply(text, parse_mode=ParseMode.MARKDOWN)
```

### Failure Logs

```
Task exception was never retrieved
future: <Task finished coro=<Dispatcher._process_polling_updates() done, defined at /usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/dispatcher.py:304> exception=CantParseEntities("Can't parse entities: can't find end of the entity starting at byte offset 4")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/dispatcher.py", line 312, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/dispatcher.py", line 172, in process_updates
    return await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/dispatcher.py", line 192, in process_update
    return await self.message_handlers.notify(update.message)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "main.py", line 16, in cmd_handler
    await message.reply(text, parse_mode=ParseMode.MARKDOWN)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/types/message.py", line 866, in reply
    reply_markup=reply_markup)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/bot/bot.py", line 217, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/bot/base.py", line 184, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, timeout=self.timeout, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/bot/api.py", line 98, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.7/dist-packages/aiogram/bot/api.py", line 72, in check_result
    exceptions.BadRequest.detect(description)
  File "/usr/local/lib/python3.7/dist-packages/aiogram/utils/exceptions.py", line 137, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.CantParseEntities: Can't parse entities: can't find end of the entity starting at byte offset 4
```

**Comment by JrooTJunior** [comment]
Is not bug.

CantParseEntities is raised by Telegram Bot API.

And if you want to use unsafe data from users in text do quote strings by md util (`from aiogram.utils import markdown`  or by alias `from aiogram import md`)

## Docs
- Quote HTML: https://aiogram.readthedocs.io/en/dev-2.x/utils/markdown.html#aiogram.utils.markdown.quote_html
- Escape Markdown: https://aiogram.readthedocs.io/en/dev-2.x/utils/markdown.html#aiogram.utils.markdown.escape_md


## Example
```python
await message.answer(f"Sender name: {md.quote_html(message.from_user.full_name)}")
```

## Other recommendations
1. Just use HTML instead of Markdown because html is more controllable and has more expectable behavior
2. Just use default `parse_mode` value. It can be configure in Bot initializer:
```python
bot = Bot(token=token, parse_mode=types.ParseMode.HTML)
```

**Comment by delimitry** [comment]
Thank you @JrooTJunior
