### ISSUE TITLE
MongoStorage in aiogram uses unmaintained library

### ISSUE THREAD

**Issue by archieruin** [aiogram/aiogram#301]
* Operating System: 18.04.4 LTS (Bionic Beaver)
* Python Version: 3.8.2
* aiogram version: 2.7
* aiohttp version: 3.6.2

## Failure Information (for bugs)

[Message](https://t.me/aiogram/4664) from telegram:
> Evgen Fil // 🔪, [10.04.20 21:24]
> Ok, aiomongo must not be used
> 
> Latest commit ... on Aug 9, 2017
> requirements.txt: pymongo == 3.4 (3.10.1 is latest for now)
> 
> => MongoStorage in aiogram uses unmaintained library.

### Failure Logs
```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from bot import handlers, utils
  File "/home/archie/subs_bot/bot/utils.py", line 16, in <module>
    from bot.handlers import messages
  File "/home/archie/subs_bot/bot/handlers/messages.py", line 10, in <module>
    from bot.filters import IsAdmin
  File "/home/archie/subs_bot/bot/filters.py", line 6, in <module>
    from bot.misc import dp
  File "/home/archie/subs_bot/bot/misc.py", line 5, in <module>
    from aiogram.contrib.fsm_storage.mongo import MongoStorage
  File "/home/archie/subs_bot/venv/lib/python3.8/site-packages/aiogram/contrib/fsm_storage/mongo.py", line 8, in <module>
    import aiomongo
  File "/home/archie/subs_bot/venv/lib/python3.8/site-packages/aiomongo/__init__.py", line 4, in <module>
    from .client import AioMongoClient
  File "/home/archie/subs_bot/venv/lib/python3.8/site-packages/aiomongo/client.py", line 5, in <module>
    from pymongo.client_options import ClientOptions
  File "/home/archie/subs_bot/venv/lib/python3.8/site-packages/pymongo/__init__.py", line 87, in <module>
    from pymongo.mongo_client import MongoClient
  File "/home/archie/subs_bot/venv/lib/python3.8/site-packages/pymongo/mongo_client.py", line 52, in <module>
    from pymongo.client_options import ClientOptions
  File "/home/archie/subs_bot/venv/lib/python3.8/site-packages/pymongo/client_options.py", line 23, in <module>
    from pymongo.pool import PoolOptions
  File "/home/archie/subs_bot/venv/lib/python3.8/site-packages/pymongo/pool.py", line 124, in <module>
    platform.linux_distribution() if part])),
AttributeError: module 'platform' has no attribute 'linux_distribution'
```

**Comment by evgfilim1** [comment]
#216 can fix this (after some refactoring)
