### ISSUE TITLE
Fail in the Quick Start code

### ISSUE THREAD

**Issue by gabrielba15** [aiogram/aiogram#305]
## Context

Hey! I've been tried follow the Quick Start Code at https://aiogram.readthedocs.io/en/latest/quick_start.html but after executing it give me an error.

I can't find enough information about this. Please wait for an answer. Thanks in advance.

* Operating System: Windows 10 
* Python Version: 3.x
* aiogram version: 2.7
* aiohttp version: I Don't know
* uvloop version (if installed): I din't install it  

## Failure Information (for bugs)

This error: 
`Exception ignored in: <function BaseBot.__del__ at 0x03D8C070>
Traceback (most recent call last):
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiogram\bot\base.py", line 109, in __del__
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 758, in new_event_loop
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\events.py", line 656, in new_event_loop
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 310, in __init__
  File "C:\Users\gabriel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 633, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03E37820>`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

My code below: 

    import logging
    from aiogram import Bot, Dispatcher, executor, types
    BOT_TOKEN = "MY BOT TOKEN"

    logging.basicConfig(level=logging.INFO)

    bot = Bot(token=BOT_TOKEN)
    dp = Dispatcher(bot)

    @dp.message_handler(commands=['start', 'help'])
    async def send_welcome(message: types.Message):
        """
        This handler will be called when user sends `/start` or `/help` command
        """
        await message.reply("Hi!\nI'm EchoBot!\nPowered by aiogram.")

**Comment by gabbhack** [comment]
This is not a bug of aiogram, but his documentation.

Use full example: https://github.com/aiogram/aiogram/blob/aec67b18aff248c87ddf6d47382c19cc9f0e77ec/examples/echo_bot.py

The problem is that the aiohttp client needs to be closed, either manually via `await bot.close()`, or automatically when using executor (as in example).
