### ISSUE TITLE
i18n.lazy_proxy not resolves to string in ReplyKeyboardMarkup.row() 

### ISSUE THREAD

**Issue by benyaming** [aiogram/aiogram#312]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Win10
* Python Version: 3.7
* aiogram version: 2.8
* aiohttp version: 3.6.2
* uvloop version (if installed): -

## Expected Behavior

`ReplyKeyboardMarkup.row()` resolved Proxy objects to strings automatically.

## Current Behavior

It's not resolves.

### Failure Logs

```
Traceback (most recent call last):
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 332, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 188, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 208, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\benyamin\PycharmProjects\zmanim_bot\zmanim_bot\handlers\menus.py", line 43, in handle_settings_menu
    await msg.reply(messages.init_settings, reply_markup=kb)
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\types\message.py", line 881, in reply
    reply_markup=reply_markup)
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\bot\bot.py", line 214, in send_message
    reply_markup = prepare_arg(reply_markup)
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\utils\payload.py", line 56, in prepare_arg
    return json.dumps(_normalize(value))
  File "C:\Users\benyamin\.virtualenvs\zmanim_bot-CP2MNxs_\lib\site-packages\aiogram\utils\json.py", line 43, in dumps
    return json.dumps(data, ensure_ascii=False)
  File "c:\users\benyamin\appdata\local\programs\python\python37-32\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\benyamin\appdata\local\programs\python\python37-32\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\benyamin\appdata\local\programs\python\python37-32\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\benyamin\appdata\local\programs\python\python37-32\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LazyProxy is not JSON serializable
```

**Comment by uwinx** [comment]
@benyaming, how can we reproduce this behavior?

**Comment by benyaming** [comment]
@uwinx, sorry for long pause. Here it is:


```
from aiogram.contrib.middlewares.i18n import I18nMiddleware

class I18N(I18nMiddleware):
    ...

i18n = I18N()
_ = i18n.lazy_gettext

kb = ReplyKeyboardMarkup()
kb.row(_('Spam'))

await bot.send_message(..., 'Welcome!', reply_markup=kb)
```
