### ISSUE TITLE
DateTimeField serialization error on Windows 10

### ISSUE THREAD

**Issue by drforse** [aiogram/aiogram#349]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Python Version: 3.8.0
* aiogram version: 2.8
* aiohttp version: 3.6.2
* uvloop version (if installed): not installed

## Expected Behavior

Serialized DateTimeField

## Current Behavior

OSError: [Errno 22] Invalid argument

## Failure Information (for bugs)

When datetime is datetime.datetime(1970, 1, 1) the serialization on Windows 10 fails with OSError

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `await bot.kick_user(chat_id, user_id)`
2. `print(await bot.get_chat_member(chat_id, user_id))`
3. you get it... no, you

### Failure Logs

```
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\projects\photo_city_bot\bot_api\endpoints\unban_users.py", line 36, in post
    print(chat_member)
  File "C:\Users\Admin\Desktop\projects\photo_city_bot\venv\lib\site-packages\aiogram\types\base.py", line 204, in __str__
    return self.as_json()
  File "C:\Users\Admin\Desktop\projects\photo_city_bot\venv\lib\site-packages\aiogram\types\base.py", line 192, in as_json
    return json.dumps(self.to_python())
  File "C:\Users\Admin\Desktop\projects\photo_city_bot\venv\lib\site-packages\aiogram\types\base.py", line 169, in to_python
    value = self.props[name].export(self)
  File "C:\Users\Admin\Desktop\projects\photo_city_bot\venv\lib\site-packages\aiogram\types\fields.py", line 95, in export
    return self.serialize(self.get_value(instance))
  File "C:\Users\Admin\Desktop\projects\photo_city_bot\venv\lib\site-packages\aiogram\types\fields.py", line 180, in serialize
    timestamp = value.timestamp()
OSError: [Errno 22] Invalid argument
```

I would fix it like that:
```
class DateTimeField(Field):
    """
    In this field st_ored datetime

    in: unixtime
    out: datetime
    """

    def serialize(self, value: datetime.datetime):
        print(value)
        if os.name == 'nt':
            timestamp = (value - datetime.datetime(1970, 1, 1)).total_seconds()
        else:
            timestamp = value.timestamp()

        return round(timestamp)

    def deserialize(self, value, parent=None):
        return datetime.datetime.fromtimestamp(value)
```
but I'm not sure if it is normal, doesn't seem to be ok to me xD

**Comment by evgfilim1** [comment]
Is it still reproducible?

**Comment by drforse** [comment]
> Is it still reproducible?

Yes.

Operating System: Windows 10
Python Version: 3.8.5
aiogram version: 2.11.2
aiohttp version: 3.7.3
uvloop version (if installed): not installed

Code:
```
from aiogram import Bot, Dispatcher, executor


bot = Bot(TOKEN)
dp = Dispatcher(bot)


@dp.message_handler(commands=['test'])
async def test(m):
    chat_id, user_id = m.chat.id, m.reply_to_message.from_user.id
    await bot.kick_chat_member(chat_id, user_id)
    print(await bot.get_chat_member(chat_id, user_id))


executor.start_polling(dp)

```

Traceback:
```
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\sit
e-packages\aiogram\dispatcher\dispatcher.py:380> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:/Users/admin/Desktop/projects/BotDaddy/test_bot.py", line 12, in test
    print(await bot.get_chat_member(chat_id, user_id))
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\types\base.py", line 204, in __str__
    return self.as_json()
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\types\base.py", line 192, in as_json
    return json.dumps(self.to_python())
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\types\base.py", line 169, in to_python
    value = self.props[name].export(self)
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\types\fields.py", line 95, in export
    return self.serialize(self.get_value(instance))
  File "C:\Users\admin\Desktop\projects\BotDaddy\venv\lib\site-packages\aiogram\types\fields.py", line 178, in serialize
    return round(value.timestamp())
OSError: [Errno 22] Invalid argument
```

**Comment by mudrakov** [comment]
> Is it still reproducible?

Yeз, what just happened with this code:
```
@dp.message_handler()
async def echo_message(message: types.Message):
    member = await bot.get_chat_member(GROUP_ID, message.from_user.id)
    if member:
        await bot.send_message(message.chat.id, message.text)
    else:
        await bot.send_message(message.chat.id, 'Sorry')

```
Traceback:
```
Task exception was never retrieved
future: <Task finished name='Task-7' coro=<Dispatcher._process_polling_updates() done, defined at C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\dispatcher\dispatcher.py:380> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\PycharmProjects\testBot\test\bot.py", line 28, in echo_message
    await bot.send_message(message.chat.id, member)
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\bot\bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\bot\base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\bot\api.py", line 137, in make_request
    req = compose_data(data, files)
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\bot\api.py", line 169, in compose_data
    data.add_field(key, str(value))
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\types\base.py", line 204, in __str__
    return self.as_json()
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\types\base.py", line 192, in as_json
    return json.dumps(self.to_python())
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\types\base.py", line 169, in to_python
    value = self.props[name].export(self)
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\types\fields.py", line 95, in export
    return self.serialize(self.get_value(instance))
  File "C:\PycharmProjects\testBot\test\lib\site-packages\aiogram\types\fields.py", line 178, in serialize
    return round(value.timestamp())
OSError: [Errno 22] Invalid argument
```

**Comment by mudrakov** [comment]
> ## Context
> I would fix it like that:
> 
> ```
> class DateTimeField(Field):
>     """
>     In this field st_ored datetime
> 
>     in: unixtime
>     out: datetime
>     """
> 
>     def serialize(self, value: datetime.datetime):
>         print(value)
>         if os.name == 'nt':
>             timestamp = (value - datetime.datetime(1970, 1, 1)).total_seconds()
>         else:
>             timestamp = value.timestamp()
> 
>         return round(timestamp)
> 
>     def deserialize(self, value, parent=None):
>         return datetime.datetime.fromtimestamp(value)
> ```
> 
> but I'm not sure if it is normal, doesn't seem to be ok to me xD

It's great works! But I'm not sure if it is normal, doesn't seem to be ok to me xDD

**Comment by malikovss** [comment]
it is only on windows?

**Comment by DLumi** [comment]
The issue still persists on the most recent Aiogram version.

### Sys info

OS: Windows 10 Pro for Workstations, build 19044.1889
python: 3.7.0
aiogram: 2.22.1
aiohttp: 3.8.0

### MRE (just an echo bot):
```python
from aiogram import Bot, Dispatcher, executor, types
from assets.config import TOKEN

bot = Bot(token=TOKEN)
dp = Dispatcher(bot)


@dp.message_handler()
async def echo(message: types.Message):
    await message.answer(message.text)


async def on_startup(dp):
    print('Bot start')


if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True, on_startup=on_startup)
```

### Steps to reproduce:
1) start the bot with the code above
2) send a random msg to the bot (to see that it's working)
3) stop the bot from TG client 
4) receive a long traceback (attached below) from the dispatcher

The bot does not react to any subsequent actions, including pressing "Restart the bot" in TG client.
Only code re-run helps to fix it (the user has to restart the bot before you re-run the code, otherwise - the same error).

### Full traceback:

```
Updates were skipped successfully.
Bot start
Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 155, in to_object
    return cls(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 181, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument
Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 155, in to_object
    return cls(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 181, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument
Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 155, in to_object
    return cls(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 181, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument
Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 155, in to_object
    return cls(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 181, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument
Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 155, in to_object
    return cls(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 181, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument
Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 155, in to_object
    return cls(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\base.py", line 97, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Anaconda3\envs\Bot\lib\site-packages\aiogram\types\fields.py", line 181, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument
Goodbye!

Process finished with exit code 0

```
