### ISSUE TITLE
RuntimeError: Timeout context manager should be used inside a task

### ISSUE THREAD

**Issue by vitaliy-diachkov** [aiogram/aiogram#365]
So, basically I want to use starlette (https://www.starlette.io/) as a webhook for telegram bot and iogram as a way to handle bot messages.

I've created an endpoint to get the telegram bot updates:

```
class UpdateTelegramBotEndpoint(HTTPEndpoint):
    async def post(self, request):
        update_data = await request.json()
        await process_update(update_data)
        return JSONResponse(update_data, status_code=200)
```

The process_update function (I actually don't know whether it is right to use .set_current() methods, but that's is not a point):
```
async def process_update(update_data: dict):
    update = Update(**update_data)

    Bot.set_current(bot)
    Dispatcher.set_current(dispatcher)

    return await dispatcher.process_update(update)
```

Message handler function:
```
bot = Bot(token=settings.TELEGRAM_API_KEY)
dispatcher = Dispatcher(bot)


@dispatcher.message_handler(commands=('start', 'help'))
async def send_help_message(message):
    await message.reply(
        '*NoteBot welcomes you!*\n\n'
        'Forward me a message from a channel to save it as Evernote note. '
        'Admit that you should grant access for me to be able to create'
        'notes for you.\n\n'
        '*Commands*:\n'
        '\t/login - Login into Evernote',
        parse_mode='Markdown'
    )
```

When I'm trying to send bot a /help message, I'm getting such error:
```
INFO:     91.108.6.40:0 - "POST /updates/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/starlette/endpoints.py", line 30, in dispatch
    response = await handler(request)
  File "/home/vitaliy/coding/telegram-evernote-bot/src/views.py", line 57, in post
    await process_update(update_data)
  File "/home/vitaliy/coding/telegram-evernote-bot/src/services/updates.py", line 13, in process_update
    return await dispatcher.process_update(update)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 214, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/home/vitaliy/coding/telegram-evernote-bot/src/bot.py", line 21, in send_help_message
    await message.reply(
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiogram/types/message.py", line 995, in reply
    return await self.bot.send_message(
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiogram/bot/bot.py", line 219, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiogram/bot/base.py", line 201, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiogram/bot/api.py", line 103, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiohttp/client.py", line 426, in _request
    with timer:
  File "/home/vitaliy/.cache/pypoetry/virtualenvs/telegram-evernote-bot-IC7bT7Nj-py3.8/lib/python3.8/site-packages/aiohttp/helpers.py", line 579, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task
```

Is there any way I can fix this? The thing I want to do is to get update from telegram api -> process it asynchronious with aiogram's bot -> send user a message.

Is there any way I can deal with it or should I use starlette and telegram bot separately (that is not prefered, as I have some other endpoints to same telegram user/chat data into my mongoDB).

**Comment by evgfilim1** [comment]
@vitaliy-diachkov Hello, thanks for reporting. For better investigation please provide an output for `python -m aiogram`.

**Comment by vitaliy-diachkov** [comment]
> @vitaliy-diachkov Hello, thanks for reporting. For better investigation please provide an output for `python -m aiogram`.

```
poetry run python3 -m aiogram
CPython: 3.8.2 (default, Apr 27 2020, 15:53:34) [GCC 9.3.0]
OS: Linux-5.4.0-37-generic-x86_64-with-glibc2.29
aiogram: 2.9.2
aiohttp: 3.6.2
uvloop: 0.14.0
JSON mode: json
```

For my thought, the problem is that dispatcher's event loop isn't initilized and I can't reset (or doesn't know the proper way) it to my starlette's (uvicorn's actually) event loop in runtime.

**Comment by evgfilim1** [comment]
Yeah, that was what I thought about. You're using uvloop (uvicorn's dependency). It's known (but not yet properly reported) bug with aiohttp, uvloop and Python 3.8 (?)

ref: MagicStack/uvloop#274

**Comment by vitaliy-diachkov** [comment]
I have already tried to set the base loop to asyncio loop, configuring unvicorn the way below:
```
uvicorn.run(
     ...,
     loop='asyncio'
)
```

But I was still getting those errors

**Comment by evgfilim1** [comment]
uvloop is still installed and can be imported, so aiogram tries to use it:
https://github.com/aiogram/aiogram/blob/21b4b64db1ba5ed8465a32279cd2efd4165b2b44/aiogram/__init__.py#L20-L26

> I have already tried to set the base loop to asyncio loop, configuring uvicorn the way below:
> 
> ```
> uvicorn.run(
>      ...,
>      loop='asyncio'
> )
> ```

Try setting `DISABLE_UVLOOP=1` environment variable together with setting asyncio loop in uvicorn.

**Comment by vitaliy-diachkov** [comment]
I've tried to set `DISABLE_UVLOOP=1`, but it caused no effect.

I've solved the problem by doing this (if it would help):
```
class UpdateTelegramBotEndpoint(HTTPEndpoint):
    async def post(self, request):
        update_data = await request.json()
        update = Update(**update_data)
        loop = asyncio.get_running_loop()
        bot = Bot(token=settings.TELEGRAM_API_KEY, loop=loop)
        dispatcher.bot = bot
        Bot.set_current(bot)
        await dispatcher.process_update(update)
        return JSONResponse(update_data, status_code=200)
```

But. as you can see, I'm creating new Bot instance each time I get the update and globally resets the dispatcher's bot property, what is a very bad practice. Hope this code example will help you to find out the solution.

**Comment by uwinx** [comment]
@vitaliy-diachkov, I strongly suggest you to avoid creating `Bot` in global scope. and creating new instance for each request is not the best you can do either. I believe, there's a nicer solution. For example, `starlette.applications.Starlette` takes `on_startup` argument which is...
- **on_startup** - A list of callables to run on application startup. Startup handler callables do not take any arguments, and may be either standard functions, or async functions.

So you may have a "fuzzy" `bot` global (I suppose you have got to use only one bot)

and...

0. Didn't quite get why are replying with an update to an incoming a webhook?

Let me know if that was helpful.

**Comment by vitaliy-diachkov** [comment]
Yeah, initializing aiogram's bot in `on_startup` function seems to be a quiet good decision.

**Comment by uwinx** [comment]
@vitaliy-diachkov, let us know here if we can close it?

Thanks for your interest and opening this issue!

**Comment by evgfilim1** [comment]
> As far as I know, [`aiohttp`](https://github.com/aio-libs/aiohttp) works perfectly with [`uvloop`](https://github.com/MagicStack/uvloop)

@uwinx it *does* work, but not with timers (at least in aiogram, IDK why)
By saying "it doesn't work" I mean timers (see traceback, @vitaliy-diachkov is not the only one who faces this, at least me too)

> let us know here if we can close it?

Don't close it as it is still a bug in aiogram

**Comment by dima-kov** [comment]
Hi team! Thank you for your input into the aiogram project!

I need to manage a thousand bots with a similar approach: one webhook with the same handling logic for each of bots. I also do not want to create a Bot instance everytime webhook is called, but what can I do?

doing this way: 
```
@dp.message_handler()
async def messages_handler(message: types.Message):
    print(message, 'YYYYYYYYES')

async def webhook(request):
    bot = Bot(token='API_TOKEN')
    dp = Dispatcher(bot)
    Bot.set_current(bot)
    Dispatcher.set_current(dp)

    update = json.loads(request.body.decode('utf-8'))
    need_to_call = []
    for responses in itertools.chain.from_iterable(await dp.process_updates([types.Update(**update)])):
        for response in responses:
            if not isinstance(response, BaseResponse):
                continue
            need_to_call.append(response.execute_response(bot))
    if need_to_call:
        try:
            await asyncio.gather(*need_to_call)
        except TelegramAPIError:
            logger.exception('Cause exception while processing updates.')

    return HttpResponse('OK')
```

And it works, but problems:
1. bot is created one every webhook call;
2. this is nod thread-safe, as I call `Bot.set_current(bot)` and `Dispatcher.set_current(dp)`

Can you advice any option to overcome this? Or it is aiogram designed such a way, so it's impossible to achive multi bots handling same webhook?
