### ISSUE TITLE
The request crash when sending the media group into the bot.

### ISSUE THREAD

**Issue by LuckyDenis** [aiogram/aiogram#373]
## Context

* Operating System: Ubuntu 20.04 LTS
* Python Version: Python 3.8.2
* aiogram version: 2.8
* aiohttp version: 3.6.2
* uvloop version (if installed): 0.14.0

## Expected Behavior

The correct handling of the request.

## Current Behavior

The request crash.

## Failure Information (for bugs)

```
DEBUG:aiogram:Response for getUpdates: [200] "'{"ok":true,"result":[{"update_id":34670330,\n"message":{"message_id":1665,"from":{"id":123456789,"is_bot":false,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","language_code":"ru"},"chat":{"id":123456789,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","type":"private"},"date":1593615557,"media_group_id":"12748924456154946","photo":[{"file_id":"AgACAgIAAxkBAAIGgV78pMQYXwk3LLlhu2jdwn6oJkN6AAKBrTEbIKToS74V5QSuu4gsL6eAki4AAwEAAwIAA20AA54-AwABGgQ","file_unique_id":"AQADL6eAki4AA54-AwAB","file_size":23164,"width":320,"height":222},{"file_id":"AgACAgIAAxkBAAIGgV78pMQYXwk3LLlhu2jdwn6oJkN6AAKBrTEbIKToS74V5QSuu4gsL6eAki4AAwEAAwIAA3gAA58-AwABGgQ","file_unique_id":"AQADL6eAki4AA58-AwAB","file_size":129120,"width":800,"height":556},{"file_id":"AgACAgIAAxkBAAIGgV78pMQYXwk3LLlhu2jdwn6oJkN6AAKBrTEbIKToS74V5QSuu4gsL6eAki4AAwEAAwIAA3kAA6A-AwABGgQ","file_unique_id":"AQADL6eAki4AA6A-AwAB","file_size":296033,"width":1280,"height":889}]}},{"update_id":34670331,\n"message":{"message_id":1666,"from":{"id":160922140,"is_bot":false,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","language_code":"ru"},"chat":{"id":160922140,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","type":"private"},"date":1593615557,"media_group_id":"12748924456154946","photo":[{"file_id":"AgACAgIAAxkBAAIGgl78pMTolBTLuDIe-0Gmv4Z6LPtoAAKCrTEbIKToS0GGnHesREu0PV_4lC4AAwEAAwIAA20AA6lvAQABGgQ","file_unique_id":"AQADPV_4lC4AA6lvAQAB","file_size":30826,"width":320,"height":208},{"file_id":"AgACAgIAAxkBAAIGgl78pMTolBTLuDIe-0Gmv4Z6LPtoAAKCrTEbIKToS0GGnHesREu0PV_4lC4AAwEAAwIAA3gAA6pvAQABGgQ","file_unique_id":"AQADPV_4lC4AA6pvAQAB","file_size":160493,"width":800,"height":521},{"file_id":"AgACAgIAAxkBAAIGgl78pMTolBTLuDIe-0Gmv4Z6LPtoAAKCrTEbIKToS0GGnHesREu0PV_4lC4AAwEAAwIAA3kAA6dvAQABGgQ","file_unique_id":"AQADPV_4lC4AA6dvAQAB","file_size":174429,"width":850,"height":554}]}},{"update_id":34670332,\n"message":{"message_id":1667,"from":{"id":123456789,"is_bot":false,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","language_code":"ru"},"chat":{"id":123456789,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","type":"private"},"date":1593615557,"media_group_id":"12748924456154946","photo":[{"file_id":"AgACAgIAAxkBAAIGg178pMRIfBei01nIed3eb1nH2ulVAAKDrTEbIKToS5qxc7tW47F5sXW5ky4AAwEAAwIAA20AA2vdAQABGgQ","file_unique_id":"AQADsXW5ky4AA2vdAQAB","file_size":25995,"width":320,"height":213},{"file_id":"AgACAgIAAxkBAAIGg178pMRIfBei01nIed3eb1nH2ulVAAKDrTEbIKToS5qxc7tW47F5sXW5ky4AAwEAAwIAA3gAA23dAQABGgQ","file_unique_id":"AQADsXW5ky4AA23dAQAB","file_size":126910,"width":800,"height":533},{"file_id":"AgACAgIAAxkBAAIGg178pMRIfBei01nIed3eb1nH2ulVAAKDrTEbIKToS5qxc7tW47F5sXW5ky4AAwEAAwIAA3kAA2zdAQABGgQ","file_unique_id":"AQADsXW5ky4AA2zdAQAB","file_size":293350,"width":1280,"height":853}]}},{"update_id":34670333,\n"message":{"message_id":1668,"from":{"id":123456789,"is_bot":false,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","language_code":"ru"},"chat":{"id":123456789,"first_name":"FIRSTNAME","last_name":"LASTNAME","username":"USERNAME","type":"private"},"date":1593615557,"media_group_id":"12748924456154946","photo":[{"file_id":"AgACAgIAAxkBAAIGhF78pMRjOhE-cKyfRK38B0oPmb71AAKErTEbIKToS8ot6OhO4IF37oMelS4AAwEAAwIAA20AA0IGAQABGgQ","file_unique_id":"AQAD7oMelS4AA0IGAQAB","file_size":13714,"width":320,"height":180},{"file_id":"AgACAgIAAxkBAAIGhF78pMRjOhE-cKyfRK38B0oPmb71AAKErTEbIKToS8ot6OhO4IF37oMelS4AAwEAAwIAA3gAA0MGAQABGgQ","file_unique_id":"AQAD7oMelS4AA0MGAQAB","file_size":76393,"width":800,"height":450},{"file_id":"AgACAgIAAxkBAAIGhF78pMRjOhE-cKyfRK38B0oPmb71AAKErTEbIKToS8ot6OhO4IF37oMelS4AAwEAAwIAA3kAA0QGAQABGgQ","file_unique_id":"AQAD7oMelS4AA0QGAQAB","file_size":191372,"width":1280,"height":720}]}}]}'"
DEBUG:aiogram.dispatcher.dispatcher:Received 4 updates.
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /$PATH/aiogram/aiogram/dispatcher/dispatcher.py:325> exception=TypeError("argument of type 'MetaTelegramObject' is not iterable")>
Traceback (most recent call last):
  File "/$PATH/aiogram/aiogram/dispatcher/dispatcher.py", line 333, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/$PATH/aiogram/aiogram/dispatcher/dispatcher.py", line 188, in process_updates
    return await asyncio.gather(*tasks)
  File "/$PATH/aiogram/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/$PATH/aiogram/aiogram/dispatcher/dispatcher.py", line 208, in process_update
    return await self.message_handlers.notify(update.message)
  File "/$PATH/aiogram/aiogram/dispatcher/handler.py", line 108, in notify
    data.update(await check_filters(handler_obj.filters, args))
  File "/$PATH/aiogram/aiogram/dispatcher/filters/filters.py", line 72, in check_filters
    f = await execute_filter(filter_, args)
  File "/$PATH/aiogram/aiogram/dispatcher/filters/filters.py", line 56, in execute_filter
    return await filter_.filter(*args, **filter_.kwargs)
  File "/$PATH/aiogram/aiogram/dispatcher/filters/filters.py", line 161, in __call__
    return await self.check(*args)
  File "/$PATH/aiogram/aiogram/dispatcher/filters/builtin.py", line 452, in check
    return types.ContentType.ANY in self.content_types or \
TypeError: argument of type 'MetaTelegramObject' is not iterable
DEBUG:aiogram:Make request: "getUpdates" with data: "{'offset': 34670334, 'timeout': 20}" and files "None"
```

### Steps to Reproduce

```
from aiogram import Bot, Dispatcher, executor
from aiogram import types
import logging

logging.basicConfig(level=logging.DEBUG)

logger = logging.getLogger(__name__)


BOT_TOKEN = "TELEGRAM-BOT-TOKEN"

bot = Bot(BOT_TOKEN)
dp = Dispatcher(bot)


@dp.message_handler()
@dp.message_handler(content_types=types.MediaGroup)
async def send_copy_message(message: types.Message):
    pass


if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True)
```

**Comment by gabbhack** [comment]
`types.MediaGroup` is not a content type. Content type is determined by the presence of a specific field in the Message object. If there is a text field, the content type is text. If there is an audio field, then the content type is audio, etc.

Telegram Bot API does not send the entire album, it sends it in separate messages with `media_group_id` field, so there is no content type for the album.

The `content_types` filter expects a string (field name) or a list of such strings. You can use a special helper [types.ContentType](https://github.com/aiogram/aiogram/blob/22094eb477711e644924eaeb2424c8cef20e637a/aiogram/types/message.py#L2179)
