### ISSUE TITLE
Connect to Telegram server is Error

### ISSUE THREAD

**Issue by koval01** [aiogram/aiogram#448]
(gpt) E:\gpt3>python bot.py
10/24/2020 18:42:35 - INFO - root -   BOT STARTED.
10/24/2020 18:42:36 - WARNING - aiogram -   Goodbye!
Traceback (most recent call last):
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\connector.py", line 946, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\asyncio\base_events.py", line 989, in create_connection
    ssl_handshake_timeout=ssl_handshake_timeout)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\asyncio\base_events.py", line 1017, in _create_connection_transport
    await waiter
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\asyncio\sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '149.154.167.220'. (_ssl.c:1091)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\bot\api.py", line 103, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\client.py", line 1083, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\client.py", line 493, in _request
    timeout=real_timeout
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\connector.py", line 528, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\connector.py", line 869, in _create_connection
    req, traces, timeout)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\connector.py", line 1023, in _create_direct_connection
    raise last_exc
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\connector.py", line 1005, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiohttp\connector.py", line 949, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.telegram.org:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '149.154.167.220'. (_ssl.c:1091)")]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 841, in <module>
    executor.start_polling(dp, loop=loop, skip_updates=False, on_shutdown=shutdown)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\utils\executor.py", line 41, in start_polling
    executor.start_polling(reset_webhook=reset_webhook, timeout=timeout, relax=relax, fast=fast)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\utils\executor.py", line 309, in start_polling
    loop.run_until_complete(self._startup_polling())
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\utils\executor.py", line 360, in _startup_polling
    await self._welcome()
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\utils\executor.py", line 350, in _welcome
    user = await self.dispatcher.bot.me
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\bot\bot.py", line 27, in me
    setattr(self, '_me', await self.get_me())
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\bot\bot.py", line 176, in get_me
    result = await self.request(api.Methods.GET_ME, payload)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\bot\base.py", line 201, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, timeout=self.timeout, **kwargs)
  File "C:\Users\Yaroslav\anaconda3\envs\gpt\lib\site-packages\aiogram\bot\api.py", line 106, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorCertificateError: Cannot connect to host api.telegram.org:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '149.154.167.220'. (_ssl.c:1091)")]
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit

(gpt) E:\gpt3>

P.S. I use Conda

**Comment by skonik** [comment]
Same issue

**Comment by vitalya420** [comment]
Same issue, when i'm trying run bot with python3.9, but works with Python3.8

**Comment by markusressel** [comment]
I get a different error message, but I think it is caused by the same issue:
```
Traceback (most recent call last):
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 946, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 103, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/client.py", line 1083, in __aenter__
    self._resp = await self._coro
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/client.py", line 490, in _request
    conn = await self._connector.connect(
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 528, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 868, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 1023, in _create_direct_connection
    raise last_exc
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 999, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiohttp/connector.py", line 953, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/markus/PycharmProjects/niles-telegram/niles_telegram/bot/__init__.py", line 131, in start
    bot_info = await self.bot.get_me()
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiogram/bot/bot.py", line 176, in get_me
    result = await self.request(api.Methods.GET_ME, payload)
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiogram/bot/base.py", line 202, in request
    return await api.make_request(self.session, self.__token, method, data, files,
  File "/home/markus/PycharmProjects/niles-telegram/venv/lib/python3.8/site-packages/aiogram/bot/api.py", line 106, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Network is unreachable]
python-BaseException

Process finished with exit code 1
```
I am running this inside a PyCharm created venv using Python 3.8.6.
I can get around this by changing this line in `aiogram/bot/base.py`:
```
# self._connector_init = dict(limit=connections_limit, ssl=ssl_context)
self._connector_init = dict(limit=connections_limit, ssl=False)
```
which is why I believe it is realted to this issue.
Of course thats not a desirable solution...
Any help/update would be very much appreciated.

**Comment by ozeranskiy** [comment]
aiohttp must be upgraded to version 3.7.1

**Comment by Rustam2900** [comment]
(venv) PS C:\Users\user\Desktop\MonthlyCalculationBot> python manage.py runbot
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @buy_a_ticket_bot id=6512722069 - 'YouTube'
INFO:aiogram.event:Update id=822091810 is handled. Duration 468 ms by bot id=6512722069
INFO:aiogram.event:Update id=822091811 is not handled. Duration 15 ms by bot id=6512722069
ERROR:aiogram.event:Cause exception while process update id=822091811 by bot id=6512722069
AttributeError: module aiohttp has no attribute get
Traceback (most recent call last):
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 49, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\fsm\middleware.py", line 42, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 170, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 142, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 137, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\router.py", line 162, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\bot\header\start.py", line 42, in check_subscription
    channels = fetch_channels()
               ^^^^^^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\bot\header\api.py", line 57, in fetch_channels
    response = aiohttp.get(f"{BASE_URL}/mandatory-users/")
               ^^^^^^^^^^^
  File "C:\Users\user\Desktop\MonthlyCalculationBot\venv\Lib\site-packages\aiohttp\__init__.py", line 240, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module aiohttp has no attribute get
