### ISSUE TITLE
Chat member failure

### ISSUE THREAD

**Issue by evolvestin** [aiogram/aiogram#579]
## Context

* Operating System: win10
* Python Version: 3.8
* aiogram version: 2.13

When user blocks or unblocks bot, bot reseve chat_member update. Then i tried to print this update and get error.

Code:
```
import aiogram
from aiogram.utils import executor
from aiogram.dispatcher import Dispatcher

dispatcher = Dispatcher(aiogram.Bot(token))

@dispatcher.my_chat_member_handler()
async def some_handler(my_chat_member: types.ChatMemberUpdated):
    print(my_chat_member)
    
if __name__ == '__main__':
    executor.start_polling(dispatcher, allowed_updates=['chat_member', 'my_chat_member', 'poll', 'poll_answer'])

```

### Failure Logs
Task exception was never retrieved
future: <Task finished name='Task-980' coro=<Dispatcher._process_polling_updates() done, defined at Python\Python38-32\lib\site-packages\aiogram\dispatcher\dispatcher.py:409> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "Python\Python38-32\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "Python\Python38-32\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "Python\Python38-32\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "Python\Python38-32\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 305, in process_update
    return await self.my_chat_member_handlers.notify(update.my_chat_member)
  File "Python\Python38-32\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:/Program Files (x86)/YandexDisk/all/bot/test-parser/worker/bot.py", line 151, in some_handler
    print(my_chat_member)
  File "Python\Python38-32\lib\site-packages\aiogram\types\base.py", line 208, in __str__
    return self.as_json()
  File "Python\Python38-32\lib\site-packages\aiogram\types\base.py", line 196, in as_json
    return json.dumps(self.to_python())
  File "Python\Python38-32\lib\site-packages\aiogram\types\base.py", line 173, in to_python
    value = self.props[name].export(self)
  File "Python\Python38-32\lib\site-packages\aiogram\types\fields.py", line 95, in export
    return self.serialize(self.get_value(instance))
  File "Python\Python38-32\lib\site-packages\aiogram\types\fields.py", line 105, in serialize
    return value.to_python()
  File "Python\Python38-32\lib\site-packages\aiogram\types\base.py", line 173, in to_python
    value = self.props[name].export(self)
  File "Python\Python38-32\lib\site-packages\aiogram\types\fields.py", line 95, in export
    return self.serialize(self.get_value(instance))
  File "Python\Python38-32\lib\site-packages\aiogram\types\fields.py", line 178, in serialize
    return round(value.timestamp())
OSError: [Errno 22] Invalid argument

Please include any relevant log snippets or files here.

**Comment by evgfilim1** [comment]
Duplicates #349
