### ISSUE TITLE
Gather doen't work with shortcuts

### ISSUE THREAD

**Issue by Forevka** [aiogram/aiogram#625]
## Context

* Operating System: windows 10/ubuntu CodeSpace
* Python Version: 3.8.6
* aiogram version: 3.x (from github)
* aiohttp version: idk
* uvloop version (if installed): idk

## Expected Behavior

asyncio.gather must work like they work with bot.* methods

## Current Behavior

asyncio.gather doen't work with shortcuts that returns methods instances like 'SendMessage'

### Steps to Reproduce

https://gist.github.com/Forevka/c70cda8a64ae9b219952f110482f2bc2

### Failure Logs

```
TypeError: unhashable type: 'SendMessage'
      Traceback (most recent call last):
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 279, in _process_update
          response = await self.feed_update(bot, update, **kwargs)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 101, in feed_update
          response = await self.update.trigger(update, bot=bot, **kwargs)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/event/telegram.py", line 135, in trigger
          return await wrapped_outer(event, kwargs)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/middlewares/error.py", line 24, in __call__
          return await handler(event, data)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 21, in __call__
          return await handler(event, data)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/fsm/middleware.py", line 38, in __call__
          return await handler(event, data)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/event/telegram.py", line 146, in _trigger
          return await wrapped_inner(event, kwargs)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/event/handler.py", line 40, in call
          return await wrapped()
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 241, in _listen_update
          response = await observer.trigger(event, update=update, **kwargs)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/event/telegram.py", line 135, in trigger
          return await wrapped_outer(event, kwargs)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/event/telegram.py", line 146, in _trigger
          return await wrapped_inner(event, kwargs)
      File "/workspaces/Aiogram.Captcha.Example/.venv/lib/python3.8/site-packages/aiogram/dispatcher/event/handler.py", line 40, in call
          return await wrapped()
      File "/workspaces/Aiogram.Captcha.Example/test.py", line 16, in command_start_handler
          gather(
      File "/opt/python/3.8.6/lib/python3.8/asyncio/tasks.py", line 820, in gather
          if arg not in arg_to_fut:
      TypeError: unhashable type: 'SendMessage'
```

## Discussion
I can make PR with fix of this behavior but i don't know how it do in better way

**Comment by Olegt0rr** [comment]
# Workaround

```python
@dp.message(commands={"a"})
async def echo_handler(message: types.Message, bot: Bot) -> None:
    texts = ["qwe1", "qwe2"]

    tasks = [
        create_task(
            bot.send_message(
                text=text,
                chat_id=message.from_user.id,
            )
        )
        for text in texts
    ]
    await gather(*tasks)
```
