### ISSUE TITLE
`message.document` is `None` after successful file upload

### ISSUE THREAD

**Issue by tropicoo** [aiogram/aiogram#641]
## Context

* Operating System: Ubuntu 20.0.4 LTS
* Python Version: 3.9.6 Alpine 3.14 Docker
* aiogram version: 2.14.2, 2.14.3
* aiohttp version: 3.7.4.post0
* uvloop version: 0.15.3

## Expected Behavior

`message.document` object is not `None` since file was uploaded sucessfully and response payload contains all needed data

## Current Behavior

`message.document` object is `None` after successful file upload

## Failure Information (for bugs)

Code:
```python
await bot.send_chat_action(chat_id=uid, action='upload_video')
message = await bot.send_document(chat_id=uid, document=file_, caption=caption)

self._log.debug(type(message))
self._log.debug(dict(message))
self._log.debug(type(message.document))

self._video_file_cache[video_path] = message.document.file_id
```

Output:
```python
[aiogram:95] - Response for sendChatAction: [200] "'{"ok":true,"result":true}'"

[aiogram:133] - Make request: "sendDocument" with data: "{'chat_id': ***, 'caption': '***'}" and files "{'document': <InputFile 'attach://AZ_fSTqJvMhlVsInAg7kcQ' with file='<_io.BufferedReader name='/dev/shm/cam_2-alert-2021-Jul-25--14-23-02-2aeaa58bed414fd29d0d67e48b56eb47.mp4'>'>}"

[aiogram:95] - Response for sendDocument: [200] "'{"ok":true,"result":{"message_id":***,"from":{"id":***,"is_bot":true,"first_name":"***","username":"***"},"chat":{"id":***,"first_name":"***","username":"***","type":"private"},"date":1627212193,"video":{"duration":7,"width":640,"height":360,"file_name":"cam_2-alert-2021-Jul-25--14-23-02-2aeaa58bed414fd29d0d67e48b.mp4","mime_type":"video/mp4","thumb":{"file_id":"***","file_unique_id":"***","file_size":23131,"width":320,"height":180},"file_id":"***","file_unique_id":"***","file_size":841149},"caption":"***","caption_entities":[{"offset":29,"length":5,"type":"bot_command"}]}}'"

[ResultAlertVideoHandler:89] - <class 'aiogram.types.message.Message'>

[ResultAlertVideoHandler:90] - {'message_id': ***, 'from': {'id': ***, 'is_bot': True, 'first_name': '***', 'username': '***'}, 'chat': {'id': ***, 'first_name': '***', 'username': '***', 'type': 'private'}, 'date': 1627212193, 'video': {'duration': 7, 'width': 640, 'height': 360, 'file_name': 'cam_2-alert-2021-Jul-25--14-23-02-2aeaa58bed414fd29d0d67e48b.mp4', 'mime_type': 'video/mp4', 'thumb': {'file_id': '***', 'file_unique_id': '***', 'file_size': 23131, 'width': 320, 'height': 180}, 'file_id': '***', 'file_unique_id': '***', 'file_size': 841149}, 'caption': '***': [{'type': 'bot_command', 'offset': 29, 'length': 5}]}

[ResultAlertVideoHandler:91] - <class 'NoneType'>

Exception in SendRecVideoTask cam_2
 Traceback (most recent call last):
   File "/opt/project/SOURCES/***/services/tasks/alarm.py", line 84, in _process_videos
     await ResultAlertVideoHandler().handle({
   File "/opt/project/SOURCES/***/handlers/abstract.py", line 25, in handle
     await self._handle(data)
   File "/opt/project/SOURCES/***/handlers/event_result.py", line 52, in _handle
     await self.__handle(data)
   File "/opt/project/SOURCES/***/handlers/event_result.py", line 67, in __handle
     await self._send_video(uid, video_path, caption, bot)
   File "/opt/project/SOURCES/***/handlers/event_result.py", line 92, in _send_video
     self._video_file_cache[video_path] = message.document.file_id
 AttributeError: 'NoneType' object has no attribute 'file_id'
```

**Comment by tropicoo** [comment]
Looks like videos with sound are _videos_, without - documents with animation. Closing.
