### ISSUE TITLE
Can't download any file to custom folder

### ISSUE THREAD

**Issue by Jsnufmars** [aiogram/aiogram#665]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 - 1809 (17763.2061)
* Python Version: 3.9.6
* aiogram version: aiogram~=2.14.3
configparser~=5.0.2
environs~=9.3.2
aioredis~=1.3.1
* aiohttp version: aiohttp 3.7.4.post0
* uvloop version (if installed): 

## Expected Behavior

Please describe the behavior you are expecting
Aren't able to dowload photo by .donwload() method. When you're making a path by yourself like 
`path = 'some_path'`
`another_path = 'another_path'`
`file_name = 'file_name.jpg'` or another like `.png`, `.jpeg` etc
and put it into
`await message.photo[-1].download(destination=f'{path}{another_path}{file_name}', make_dirs=True)`
it drops with an issue like 
```
>>>dest = destination if isinstance(destination, io.IOBase) else open(destination, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: <<<
```

Aiogram wont make dir that I needed

### Steps to Reproduce
If it takes a long path like path/path 
which should create both of folders named path and path and put here an image that downloaded by sending through telegram
```python
@dp.message_handler(content_types=["photo"])
async def download_photo(message: types.Message):
    path = 'path/path'
    image = 'image.jpg'
    await message.photo[-1].download(destination=f'{path}/{image}', make_dirs=True)
```
if it tries to make path with no .directory
```python
@dp.message_handler(content_types=["photo"])
async def download_photo(message: types.Message):
    path = 'path'
    image = 'image.jpg'
    await message.photo[-1].download(destination=f'{path}/{image}', make_dirs=True)
```
Or current dir
```python
@dp.message_handler(content_types=["photo"])
async def download_photo(message: types.Message):
    path = 'path'
    image = 'image.jpg'
    await message.photo[-1].download(destination=f'./{path}/{image}', make_dirs=True)
```
even if it takes something like current directory.

or something like that - w/o VARs but with argument ('make_dirs=False')
```python
@dp.message_handler(content_types=["photo"])
async def download_photo(message: types.Message):
    await message.photo[-1].download(destination=f'./path/image.jpg', make_dirs=False) <<<

dest = destination if isinstance(destination, io.IOBase) else open(destination, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: './path/image.jpg'

future: <Task finished name='Task-14' coro=<Dispatcher._process_polling_updates() done, defined at D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:409> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:\projects\own_temp\__main__.py", line 47, in download_photo
    await message.photo[-1].download(destination=f'./path/image.jpg', make_dirs=False)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\types\mixins.py", line 34, in download
    return await self.bot.download_file(file_path=file.file_path, destination=destination, timeout=timeout,
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\bot\base.py", line 235, in download_file
    dest = destination if isinstance(destination, io.IOBase) else open(destination, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: './path/image.jpg'
```
Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs
```python
future: <Task finished name='Task-11' coro=<Dispatcher._process_polling_updates() done, defined at D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:409> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 417, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 238, in process_updates
    return await asyncio.gather(*tasks)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 259, in process_update
    return await self.message_handlers.notify(update.message)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "D:\projects\own_temp\__main__.py", line 47, in download_photo
    await message.photo[-1].download(destination='./news/file12', make_dirs=True)
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\types\mixins.py", line 34, in download
    return await self.bot.download_file(file_path=file.file_path, destination=destination, timeout=timeout,
  File "D:\projects\own_temp\.venv\lib\site-packages\aiogram\bot\base.py", line 235, in download_file
    dest = destination if isinstance(destination, io.IOBase) else open(destination, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: './news/file12'
```
Please include any relevant log snippets or files here.

BUT!!!!!! If you have created a path and download your file into path you had created you can donwload this one with no problem. And if you had created a path and put your file into the path Aiogram create own folder named photos and put here its downloaded photo!!! What is this?

If you want to pm me - my own telegram is @Rizle

**Comment by MasterGroosha** [comment]
Too difficult to read, please suggest fixing your issue text (e.g. formatting, typos etc.)
I did some tests too with aiogram 2.14.3 on Linux, Python 3.8

```python
@dp.message_handler(content_types="photo")
async def get_photo(message: types.Message):
    await message.photo[-1].download("customdir/photo1.jpg", make_dirs=False)
```
It doesn't matter whether I user `make_dirs=True` or `make_dirs=False`. The code above downloads image to `customdir/photo1.jpg`.

**Comment by MasterGroosha** [comment]
This is where (most likely) the problem is: https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/mixins.py#L23-L32

```python
        is_path = True
        if destination is None:
            destination = file.file_path
        elif isinstance(destination, (str, pathlib.Path)) and os.path.isdir(destination):
            destination = os.path.join(destination, file.file_path)
        else:
            is_path = False

        if is_path and make_dirs:
            os.makedirs(os.path.dirname(destination), exist_ok=True)
```

Consider the handler above.
First, `is_path` is True
`if destination is None` is False, so we proceed

`elif isinstance(destination, (str, pathlib.Path)) and os.path.isdir(destination)`
The first one `isinstance(destination, (str, pathlib.Path))` is True, however `os.path.isdir(destination)` is False (since it's not a dir), so the overall is False

Then we fall into `else: is_path = False`.

The next piece of code:
```python
        if is_path and make_dirs:
            os.makedirs(os.path.dirname(destination), exist_ok=True)
```
is skipped, because `is_path` (False) and `make_dirs` always result in False.
The directory is not created, leading to FileNotFound error

**Comment by Olegt0rr** [comment]
/me updated topic message with correct code highlighting

**Comment by Olegt0rr** [comment]
@MasterGroosha 

It seems that next solution should works correctly. Could you test it?
```python
class Downloadable:
    async def download(self, destination=None, timeout=30, chunk_size=65536, seek=True, make_dirs=True):
        file, destination = self._prepare_destination(destination, make_dirs=make_dirs)
        return await self.bot.download_file(
            file_path=file.file_path,
            destination=destination,
            timeout=timeout,
            chunk_size=chunk_size,
            seek=seek,
        )

    def _prepare_destination(self, destination, make_dirs):
        file = await self.get_file()
        
        if destination is None:
            return file, file.file_path
            
        if isinstance(destination, (str, pathlib.Path)):
            destination = os.path.join(destination, file.file_path)

        if make_dirs:
            os.makedirs(os.path.dirname(destination), exist_ok=True)
        
        return file, destination
```

**Comment by MasterGroosha** [comment]
@Olegt0rr I see several issues with your code:
First, `_prepare_destination` mush be async function, because `file = await self.get_file()` (also you should call it as `await self._prepare_destination(...)`)

Second, consider the following code:
```python
@dp.message_handler(content_types="photo")
async def test_download_photo(message: types.Message):
    await message.photo[-1].download(destination="somedir/photo.jpg", make_dirs=True)
```

If `somedir` directory doesn't exist, the code works without errors, but the resulting path is 
`somedir/photo.jpg/photos/file_83.jpg` (photo.jpg is a directory name too). So, I guess, some additional checks are needed

**Comment by darksidecat** [comment]
@Olegt0rr, slightly modified your solution and added variants to the @MasterGroosha  test.

```python3
async def _prepare_destination(self, destination, make_dirs):
    file = await self.get_file()

    if destination is None:
        return file, destination

    if isinstance(destination, IOBase):
        return file, destination

    if not isinstance(destination, (str, pathlib.Path)):
        raise TypeError("destination must be str, pathlib.Path or io.IOBase type")

    if make_dirs:
        os.makedirs(os.path.dirname(destination), exist_ok=True)

    return file, destination
```

tests:

```python3
@dp.message_handler(content_types="photo")
async def test_download_photo(message: types.Message):
    # return io.BytesIO object
    i1 = await message.photo[-1].download()

    # download to i2 io.BytesIO
    i2 = BytesIO()
    await message.photo[-1].download(destination=i2)

    # make dir and save file
    await message.photo[-1].download(destination="somedir/photo.jpg", make_dirs=True)

    # FileNotFoundError exception
    try:
        await message.photo[-1].download(destination="somedir2/photo.jpg", make_dirs=False)
    except FileNotFoundError as err:
        print(err)
```
