### ISSUE TITLE
SOCKS5 proxy not works in some examples

### ISSUE THREAD

**Issue by a6a3uh** [aiogram/aiogram#77]
---
name: Bug with SOCKS5 proxy authentication
about: Works unreliably with SOCKS5 proxy authentication giving errors from time to time.

---

## Context

I'm using a socks5 proxy with authentication. Tried to put credentials both in address string and pass with `proxy_auth` as `aiohttp.BasicAuth`. And getting `aiohttp_socks.errors.SocksError: Address type not supported`

* Operating System: Ubuntu 18.10
* Python Version: 3.7
* aiogram version: 2.0.dev1 (latest dev-2.x branch HEAD, commit 8ef279bba10de40c4435715875fd2c4186efd959)
* aiohttp version: 3.4.4
* uvloop version (if installed): no

## Failure Information (for bugs)

Nevertheless there is a [bug](https://github.com/aiogram/aiogram/issues/71) resolved I still facing issues with socks5 proxy authentication. 

### Steps to Reproduce

Either use URL with credentials of this kind
`socks5://user:pass@xx.xx.xx.xx:yy/`
and provide no `proxy_auth` to `Bot`.

or use URL of kind  `socks5://xx.xx.xx.xx:yy/`
and provide `proxy_auth`  like `aiohttp.BasicAuth(login='user', password='pass')`

Both methods doesn't fail immediately. They even are capable of receiving some messages and give response. But both are fail with logs provided below. Looks like first with credentials in the string works a bit more reliable. 

You can reproduce the bug with `finite_state_machine_example.py` and `media_group.py` gives the same error if you provide them with socks5 proxy. `echo_bot.py` gives same error on request of the picture.

### Failure Logs

```
> python finite_state_machine_example.py
Skipped 1 updates.
Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiogram-2.0.dev1-py3.7.egg/aiogram/dispatcher/dispatcher.py", line 261, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiogram-2.0.dev1-py3.7.egg/aiogram/bot/bot.py", line 101, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload, timeout=timeout + 2 if timeout else None)
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiogram-2.0.dev1-py3.7.egg/aiogram/bot/base.py", line 115, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, **kwargs)
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiogram-2.0.dev1-py3.7.egg/aiogram/bot/api.py", line 97, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp/client.py", line 855, in__aenter__
    self._resp = await self._coro
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp/client.py", line 370, in_request
    timeout=timeout
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp/connector.py", line 445,in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp/connector.py", line 757,in _create_connection
    req, traces, timeout)
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp/connector.py", line 862,in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp_socks/connector.py", line 50, in _wrap_create_connection
    await sock.connect((host, port))
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp_socks/proto.py", line 150, in connect
    await self.negotiate()
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp_socks/proto.py", line 366, in negotiate
    await self._socks_connect()
  File "/home/ali/miniconda3/envs/telebot/lib/python3.7/site-packages/aiohttp_socks/proto.py", line 306, in _socks_connect
    raise SocksError(SOCKS5_ERRORS.get(err_code, 'Unknown error'))
aiohttp_socks.errors.SocksError: Address type not supported
```

**Comment by JrooTJunior** [comment]
If you want to use Socks4/5 proxy you can't use BasicAuth because [aiohttp_socks](https://github.com/romis2012/aiohttp-socks) don't provide this type of authentication.

**Comment by a6a3uh** [comment]
And that's why I've tried plain string authentication as well (like this `socks5://user:pass@xx.xx.xx.xx:yy/`) with the same results. Or plain string are not working too?

One more time. Normal messaging is working well this way. But as soon as I try to use something different like picture sending (see examples that are not working listed in my issue description) I get an error I described.

Could you pls give a short example how socks authentication should be done?

**Comment by JrooTJunior** [comment]
```python
proxy = 'socks5://ip:port'
login = 'login'
password = 'password'

bot = Bot(token=API_TOKEN, proxy=proxy, proxy_auth=BasicAuth(login, password))
```
It's worked for me :man_shrugging:

**Comment by a6a3uh** [comment]
I tried this as well. It works until you try one of examples which fails. I
listed those. So normal messaging works. Anything else fails.

**Comment by vhsw** [comment]
You should use aiosocksy.Socks5Auth() for proxy_auth.

**Comment by JrooTJunior** [comment]
> You should use aiosocksy.Socks5Auth() for proxy_auth.

Nope.
For 1.x (current stable) - yes
In 2.x used aiohttp_socks instead of aiosocksy.

**Comment by JrooTJunior** [comment]
Is this problem still relevant?

**Comment by a6a3uh** [comment]
The problem is Bot object acccepts either 

     proxy: Optional[String]

or
 
    proxy_auth: Optional[aiohttp.helpers.BasicAuth] 

it does not accepts anything from aiohttp_socks like `SocksConnector.from_url(...)`

Could you pls provide with code snippet on how to use aiohttp_socks with aiogram's Bot object?

**Comment by JrooTJunior** [comment]
It doesn't accept anything from `SocksConnector.from_url(...)` because this method implemented inside bot initializator: https://github.com/aiogram/aiogram/blob/master/aiogram/bot/base.py#L65
Thats mean what you can use url's like `socks5://username:password@host:port` as value for proxy argument.

**Comment by a6a3uh** [comment]
Well that's what I did. I've tried both. And they mostly worked but sometimes gave an error as I described. Maybe this error is not about proxying. But about implementation of some advanced features as I never get errors with normal texting but get them only on specific examples listed above.
