### ISSUE TITLE
[3.x] lazy_gettext doesn't work in text filters

### ISSUE THREAD

**Issue by asimaranov** [aiogram/aiogram#786]
Text filter doesn't suport lazy_gettext now. Code
```python
import logging

from aiogram import Bot, Dispatcher, F
from aiogram.dispatcher.filters import Text
from aiogram.types import Message
from aiogram.utils.i18n import lazy_gettext as __

TOKEN = "42:TOKEN"
dp = Dispatcher()

logger = logging.getLogger(__name__)


@dp.message(Text(text=__('Test')))
async def test(message: Message) -> None:
    await message.answer(f"Hello, <b>{message.from_user.full_name}!</b>")


def main() -> None:
    bot = Bot(TOKEN, parse_mode="HTML")

    dp.run_polling(bot)


if __name__ == "__main__":
    main()
```
Produсes
```python
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/project/test.py", line 14, in <module>
    @dp.message(Text(text=__('Test')))
  File "pydantic/main.py", line 404, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1040, in pydantic.main.validate_model
  File "pydantic/fields.py", line 723, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 899, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 699, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "text_ForwardRef('LazyProxy')" not yet prepared so type is still a ForwardRef, you might need to call Text.update_forward_refs().
```

Magic filter also doesn't work with lazy_gettext. 
```python
import logging

from aiogram import Bot, Dispatcher, F
from aiogram.types import Message
from aiogram.utils.i18n import lazy_gettext as __, I18n, ConstI18nMiddleware

from settings import LOCALES_DIR, I18N_DOMAIN

TOKEN = "42:token"
dp = Dispatcher()

logger = logging.getLogger(__name__)


# LookupError: I18n context is not set
@dp.message(F.text == __('Test'))
async def test1(message: Message) -> None:
    await message.answer(f"Hello, <b>{message.from_user.full_name}!</b>")


def main() -> None:
    bot = Bot(TOKEN, parse_mode="HTML")
    i18n = I18n(path=LOCALES_DIR, default_locale="ru", domain=I18N_DOMAIN)

    dp.message.middleware(ConstI18nMiddleware(locale='en', i18n=i18n))
    dp.run_polling(bot)


if __name__ == "__main__":
    main()
```
If I send 'Test' command to the bot the following exception will be produced: 
```python
LookupError: I18n context is not set
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 101, in feed_update
    response = await self.update.wrap_outer_middleware(self.update.trigger, update, kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 24, in __call__
    return await handler(event, data)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/fsm/middleware.py", line 36, in __call__
    return await handler(event, data)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 239, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 202, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 124, in _wrapped
    return await self._propagate_event(
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 137, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 232, in trigger
    result, data = await handler.check(event, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 79, in check
    check = await event_filter.call(*args, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 47, in call
    return await loop.run_in_executor(None, wrapped)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/magic_filter/magic.py", line 75, in resolve
    return self._resolve(value=value)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/magic_filter/magic.py", line 58, in _resolve
    value = operation.resolve(value=value, initial_value=initial_value)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/magic_filter/operations/comparator.py", line 18, in resolve
    return self.comparator(value, resolve_if_needed(self.right, initial_value=initial_value))
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/babel/support.py", line 243, in __eq__
    return self.value == other
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/babel/support.py", line 184, in value
    value = self._func(*self._args, **self._kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/utils/i18n/context.py", line 15, in gettext
    return get_i18n().gettext(*args, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/utils/i18n/context.py", line 10, in get_i18n
    raise LookupError("I18n context is not set")
LookupError: I18n context is not set

```

**Comment by asimaranov** [comment]
To fix second case I need to use
```
    dp.message.outer_middleware(ConstI18nMiddleware(locale='en', i18n=i18n))

```
Instead of
```
    dp.message.middleware(ConstI18nMiddleware(locale='en', i18n=i18n))

```
