### ISSUE TITLE
[3.x] Not informative exception stacktrace in magick filters

### ISSUE THREAD

**Issue by asimaranov** [aiogram/aiogram#788]
If there's an exception in magick filter, it's stacktrace looks like
```python
LookupError: I18n context is not set
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 235, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 101, in feed_update
    response = await self.update.wrap_outer_middleware(self.update.trigger, update, kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 24, in __call__
    return await handler(event, data)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 23, in __call__
    return await handler(event, data)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/fsm/middleware.py", line 36, in __call__
    return await handler(event, data)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 239, in trigger
    return await wrapped_inner(event, kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 202, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 124, in _wrapped
    return await self._propagate_event(
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 137, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 232, in trigger
    result, data = await handler.check(event, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 79, in check
    check = await event_filter.call(*args, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 47, in call
    return await loop.run_in_executor(None, wrapped)
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/magic_filter/magic.py", line 75, in resolve
    return self._resolve(value=value)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/magic_filter/magic.py", line 58, in _resolve
    value = operation.resolve(value=value, initial_value=initial_value)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/magic_filter/operations/comparator.py", line 18, in resolve
    return self.comparator(value, resolve_if_needed(self.right, initial_value=initial_value))
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/babel/support.py", line 243, in __eq__
    return self.value == other
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/babel/support.py", line 184, in value
    value = self._func(*self._args, **self._kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/utils/i18n/context.py", line 15, in gettext
    return get_i18n().gettext(*args, **kwargs)
  File "/Users/user/PycharmProjects/project/venv/lib/python3.9/site-packages/aiogram/utils/i18n/context.py", line 10, in get_i18n
    raise LookupError("I18n context is not set")
LookupError: I18n context is not set

```
So it doesn't contain any information about handler where it happens. 
And it's difficult to understand what filter caused the exception

**Comment by JrooTJunior** [comment]
This issue is not related to magic filter, this error means that you don't have i18n context at this place, you should use lazy gettext in filters
