### ISSUE TITLE
TimoutError: asyncio.TimeoutError from None

### ISSUE THREAD

**Issue by akarsh1995** [aiogram/aiogram#790]
```
Traceback (most recent call last):
  File "/opt/python3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/python3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/workspace/frontend/__main__.py", line 20, in <module>
    start_webhook(
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/utils/executor.py", line 99, in start_webhook
    executor = set_webhook(dispatcher=dispatcher,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/utils/executor.py", line 78, in set_webhook
    executor.set_webhook(webhook_path, route_name=route_name, web_app=web_app)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/utils/executor.py", line 289, in set_webhook
    self.loop.run_until_complete(self._startup_webhook())
  File "/opt/python3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/utils/executor.py", line 398, in _startup_webhook
    await self._welcome()
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/utils/executor.py", line 361, in _welcome
    user = await self.dispatcher.bot.me
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/bot/bot.py", line 30, in me
    setattr(self, '_me', await self.get_me())
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/bot/bot.py", line 228, in get_me
    result = await self.request(api.Methods.GET_ME, payload)
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/bot/base.py", line 226, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiohttp/client.py", line 634, in _request
    break
  File "/layers/google.python.pip/pip/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
```

* Operating System: Alpine Linux
* Python Version: 3.9
* aiogram version: 2.17.1
* aiohttp version: 3.8.1

## Current Behavior

This issue also leads to the late reply even into the webhook.

I'm currently using google app engine to host the bot.

**Comment by dh0d** [comment]
It seems I have a similar issue with echo_bot example:
```ERROR:aiogram.dispatcher.dispatcher:Cause exception while getting updates.
Traceback (most recent call last):
  File "/home/dima/.local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 383, in start_polling
    updates = await self.bot.get_updates(
  File "/home/dima/.local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/home/dima/.local/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/home/dima/.local/lib/python3.8/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/home/dima/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/dima/.local/lib/python3.8/site-packages/aiohttp/client.py", line 619, in _request
    break
  File "/home/dima/.local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError```

Python Version: 3.8.10
aiogram version: 2.14.3
aiohttp version: 3.7.4

**Comment by dh0d** [comment]
Checked with:
python 3.9.5 and aiogram 2.18 - the same

Seems it happens when there are few messages in updates.

Steps to reproduce (with [echo_bot](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/echo_bot.py)) :
- Stop the bot
- send few messages in telegram (getUpdates should return few messages)
- start the bot.

Just the last message will be responded and after some time TimeoutError will be raised.

**Comment by dh0d** [comment]
it seems the problem with my local env and the same code works well if to run on aws instance.

**Comment by akarsh1995** [comment]
To me the issue seems to be the delay in instance startup time.

Specifically for google app engine standard environment instance, to resolve the issue I added ah warmup request.
[Configure warm up request for python3 standard env](https://cloud.google.com/appengine/docs/standard/python3/configuring-warmup-requests)

**Comment by Olegt0rr** [comment]
So you can add warmup logics in `on_startup` function

**Comment by JsonUser42** [comment]
what i have to do, if i use simple server on Ubuntu 18.04+ or Docker Image with python 3.8
i've tried many things...

**Comment by akarsh1995** [comment]
> So you can add warmup logics in `on_startup` function

``` 
 ​#!/usr/bin/env python3 
  
 ​import​ ​logging 
 ​from​ ​aiogram​ ​import​ ​executor 
 ​from​ ​aiogram​.​utils​.​executor​ ​import​ ​Executor​, ​set_webhook 
 ​from​ ​frontend​.​bot​ ​import​ ​on_startup​, ​on_shutdown​, ​get_dispatcher​, ​WEBHOOK_PATH 
 ​import​ ​config 
 ​from​ ​aiohttp​ ​import​ ​web 
  
 ​# webserver settings 
 ​WEBAPP_HOST​ ​=​ ​"0.0.0.0"​  ​# or ip 
 ​WEBAPP_PORT​ ​=​ ​config​.​TG_PORT 
  
  
 ​async​ ​def​ ​ah_warmup​(​request​): 
 ​    ​return​ ​web​.​Response​(​text​=​""​, ​status​=​200​) 
  
  
 ​def​ ​setup_gae_warmup_request​(​executor​: ​Executor​): 
 ​    ​app​ ​=​ ​executor​.​web_app 
 ​    ​app​.​add_routes​([​web​.​get​(​"/_ah/warmup"​, ​ah_warmup​)]) 
 ​    ​executor​.​set_web_app​(​app​) 
  
  
 ​if​ ​__name__​ ​==​ ​"__main__"​: 
 ​    ​logging​.​info​( 
 ​        ​"Using HOST: {}, PORT: {} to spin up the webserver."​.​format​( 
 ​            ​WEBAPP_HOST​, ​WEBAPP_PORT 
 ​        ) 
 ​    ) 
 ​    ​if​ ​config​.​IS_PROD_ENV​: 
 ​        ​executor​ ​=​ ​set_webhook​( 
 ​            ​webhook_path​=​WEBHOOK_PATH​, 
 ​            ​on_startup​=​on_startup​, 
 ​            ​on_shutdown​=​on_shutdown​, 
 ​            ​dispatcher​=​get_dispatcher​(), 
 ​            ​skip_updates​=​True​, 
 ​        ) 
 ​        ​if​ ​config​.​GAE_SERVICE​: 
 ​            ​setup_gae_warmup_request​(​executor​) 
 ​        ​executor​.​run_app​( 
 ​            ​host​=​WEBAPP_HOST​, 
 ​            ​port​=​WEBAPP_PORT​, 
 ​        ) 
 ​    ​else​: 
 ​        ​executor​.​start_polling​(​get_dispatcher​(), ​skip_updates​=​True​)```
