### ISSUE TITLE
ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default Connect call failed

### ISSUE THREAD

**Issue by alexvas96** [aiogram/aiogram#819]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 20.04.3 LTS (Focal Fossa)
* Python Version: 3.8
* aiogram version: 2.18
* aiohttp version: 3.8.1
* uvloop version (if installed): 

## Current Behavior

After bot start:

```
Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('149.154.167.220', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Connect call failed ('149.154.167.220', 443)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/site-packages/aiogram/bot/api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Connect call failed ('149.154.167.220', 443)]
```

**Comment by losimen** [comment]
I am using Google Cloud Compute Engine to host my telegram bot. And the same issue appeared not the first time, [here you can see log file](https://drive.google.com/file/d/1VDJJ-FmM6hNYbO5Q1QBI-dDL7U2ywtM6/view?usp=sharing).  Also, [stack over flow question](https://stackoverflow.com/questions/70815608/traceback-cannot-connect-to-host-api-telegram-org443), with the same problem without an answer

**Comment by evgfilim1** [comment]
Is it ok now?

**Comment by evgfilim1** [comment]
> > Is it ok now?
> 
> Yeah, I have explained my solution before.

I'm asking @alexvas96 if the issue is still relevant.

**Comment by alexvas96** [comment]
Yes, it's ok now. After that time this problem didn't happen .

**Comment by MarfelEvgen** [comment]
I solved this problem by adding a proxy https://docs.aiogram.dev/en/latest/examples/proxy_and_emojize.html
there are other solutions to this problem on the pythonanywhere.com forum

**Comment by extym** [comment]
> The problem is that time on your host machine is different from world time. I have noticed that Google Cloud compute engine doesn't have any time synchronization services. That explains why the bot works well for two days, and then he starts catching tracebacks.

What is  different -  can say more specific? server: date >>> Fri 24 Feb 2023 10:26:32 AM GMT

**Comment by losimen** [comment]
> > The problem is that time on your host machine is different from world time. I have noticed that Google Cloud compute engine doesn't have any time synchronization services. That explains why the bot works well for two days, and then he starts catching tracebacks.
> 
> What is different - can say more specific? server: date >>> Fri 24 Feb 2023 10:26:32 AM GMT

World time Fri 24 Feb 2023 10:26:32 AM GMT
At the same time internal server time is Fri 24 Feb 2023 10:23:32 AM GMT.

**Comment by owiashacker** [comment]
What is the solution to this problem?


Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client.py", line 586, in _request
    await resp.start(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\client_reqrep.py", line 905, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 386, in start_polling
    allowed_updates=allowed_updates
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\base.py", line 237, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, timeout=self.timeout, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\api.py", line 142, in make_request
    raise exceptions.NetworkError(f"aiohttp client throws an error: {e.__class__.__name__}: {e}")
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [WinError 10054] An existing connection was forcibly closed by the remote host
Cause exception while getting updates.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 386, in start_polling
    allowed_updates=allowed_updates
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\base.py", line 237, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, timeout=self.timeout, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\aiogram\bot\api.py", line 111, in check_result
    raise exceptions.RetryAfter(parameters.retry_after)
aiogram.utils.exceptions.RetryAfter: Flood control exceeded. Retry in 5 seconds.






python = 3.7
aiogram = 2.25.2
python-telegram-bot = 12.0.0
