### ISSUE TITLE
Cannot install aiogram from tar.gz archive 

### ISSUE THREAD

**Issue by rominf** [aiogram/aiogram#84]
---
name: Bug report
about: Create a report to help us improve

---

## Context
* Operating System: GNU/Linux 4.18.7-1-default, openSUSE Tumbleweed
* Python Version: 3.7.0
* aiogram version: 2.0
* aiohttp version: Irrelevant
* uvloop version (if installed): Irrelevant

## Expected Behavior
I run `pip install https://files.pythonhosted.org/packages/b8/78/64dff7c69f21df0383bf442060a44c4dbf8842bd454c03858c11fa483330/aiogram-2.0.tar.gz` and it installs fine.

## Current Behavior
```shell
$ pip install https://files.pythonhosted.org/packages/b8/78/64dff7c69f21df0383bf442060a44c4dbf8842bd454c03858c11fa483330/aiogram-2.0.tar.gz       
Looking in indexes: https://pypi.kama.gs/tech/index, https://pypi.org/simple
Collecting https://files.pythonhosted.org/packages/b8/78/64dff7c69f21df0383bf442060a44c4dbf8842bd454c03858c11fa483330/aiogram-2.0.tar.gz                               
  Using cached https://files.pythonhosted.org/packages/b8/78/64dff7c69f21df0383bf442060a44c4dbf8842bd454c03858c11fa483330/aiogram-2.0.tar.gz                           
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/home/rominf/.pyenv/versions/3.7.0/envs/kgjirabot-3.7.0/lib/python3.7/site-packages/pip/_internal/download.py", line 437, in get_file_content              
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-7tlnzhry/requirements.txt'                                                             

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-7tlnzhry/setup.py", line 82, in <module>
        install_requires=get_requirements()
      File "/tmp/pip-req-build-7tlnzhry/setup.py", line 58, in get_requirements
        return [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-req-build-7tlnzhry/setup.py", line 58, in <listcomp>
        return [str(ir.req) for ir in install_reqs]
      File "/home/rominf/.pyenv/versions/3.7.0/envs/kgjirabot-3.7.0/lib/python3.7/site-packages/pip/_internal/req/req_file.py", line 80, in parse_requirements         
        filename, comes_from=comes_from, session=session
      File "/home/rominf/.pyenv/versions/3.7.0/envs/kgjirabot-3.7.0/lib/python3.7/site-packages/pip/_internal/download.py", line 441, in get_file_content              
        'Could not open requirements file: %s' % str(exc)
    pip._internal.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: '/tmp/pip-req-build-7tlnzhry/requirements.txt'  

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-7tlnzhry/ 
```

### Steps to Reproduce
Run the command above.

### Failure Logs
See above.

## Why?
I need this because access to pypi.org is blocked and I want to install from archive (it can be downloaded before the installation).

**Comment by JrooTJunior** [comment]
Oh. That's intresting issue. I'll try to fix it but now you can install it from github: `pip install git+https://github.com/aiogram/aiogram.git`

**Comment by JrooTJunior** [comment]
Or:
``` bash
git clone https://github.com/aiogram/aiogram.git
cd aiogram
python setup.py install
```

**Comment by rominf** [comment]
Thank you, I'll wait for installation from the archive because I cannot use git.

**Comment by JrooTJunior** [comment]
Fixed in dev-2.x branch. Will be available from pypi soon.

**Comment by rominf** [comment]
@JrooTJunior, nice!
Can you fix this for the 1.x branch? It's not hard to do, but there are people, who need this fix.

**Comment by JrooTJunior** [comment]
I can do that but without publishing on PyPi if it will help you.
But installing from git works as well without that fix.

**Comment by rominf** [comment]
Ok, I can cherry-pick this commit and apply to the 1.x branch myself. Anyway, I have to maintain my own version of 1.x branch.
