### ISSUE TITLE
Bad request when sending a BytesIO object directly derived from the downloaded one

### ISSUE THREAD

**Issue by carolhmj** [aiogram/aiogram#87]
I ran into this weird issue when implementing my bot, so I thought about sending it here.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 18.04
* Python Version: 3.7.0
* aiogram version: 2.0
* aiohttp version: 3.4.4
* uvloop version (if installed): 0.11.3 

## Current Behavior

I'm using a image library to do some transformations in images sent by the user, but I managed to reproduce the issue without it. Basically, when I download an image using the download_file_by_id function and write its byte contents into another BytesIO Object (standing in for the Image type in the image library), then send this second BytesIO object with send_photo, I get an error.

### Steps to Reproduce

I created a simple test bot to reproduce the steps:

`import logging

from aiogram import Bot, Dispatcher, executor, types
from aiogram.types import ContentTypes
from bot_info import API_TOKEN
from io import BytesIO

# Configure logging
logging.basicConfig(level=logging.INFO)

# Initialize bot and dispatcher
bot = Bot(token=API_TOKEN)
dp = Dispatcher(bot)

@dp.message_handler(content_types=ContentTypes.PHOTO)
async def test(message: types.Message):
	downloaded = await bot.download_file_by_id(message.photo[-1].file_id)
	b = BytesIO()
	b.write(downloaded.getvalue())
	with open('testfile.jpg', 'wb') as f:
		f.write(b.getvalue())
	await bot.send_photo(message.chat.id, b)

if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True)`

I managed to get around this bug by saving the BytesIO content into a intermediate file, then immediately opening this intermediate file and sending it in the send_photo method.

### Failure Logs

The error stack trace is as follows:
`ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Dispatcher._process_polling_updates() done, defined at /home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py:265> exception=BadRequest('Bad request: file must be non-empty')>
Traceback (most recent call last):
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in process_updates
    return await asyncio.gather(*tasks)
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/dispatcher/handler.py", line 99, in notify
    response = await handler(*args, **partial_data)
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/dispatcher/dispatcher.py", line 168, in process_update
    return await self.message_handlers.notify(update.message)
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/dispatcher/handler.py", line 99, in notify
    response = await handler(*args, **partial_data)
  File "test_bot.py", line 23, in send_welcome
    await bot.send_photo(message.chat.id, b)
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/bot/bot.py", line 284, in send_photo
    result = await self.request(api.Methods.SEND_PHOTO, payload, files)
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/bot/base.py", line 112, in request
    proxy=self.proxy, proxy_auth=self.proxy_auth, **kwargs)
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/bot/api.py", line 98, in make_request
    return await check_result(method, response.content_type, response.status, await response.text())
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/bot/api.py", line 72, in check_result
    exceptions.BadRequest.detect(description)
  File "/home/carol/.pyenv/versions/3.7.0/lib/python3.7/site-packages/aiogram/utils/exceptions.py", line 117, in detect
    raise cls(description)
aiogram.utils.exceptions.BadRequest: Bad request: file must be non-empty
`

**Comment by JrooTJunior** [comment]
Before sending io.BytesIO object you need to move pointer to start of buffer (`b.seek(0)`)

**Comment by carolhmj** [comment]
Thanks! It worked
