### ISSUE TITLE
[3.x] `i18n` exception on `ChatJoinRequest` 

### ISSUE THREAD

**Issue by Olegt0rr** [aiogram/aiogram#870]
## Context

Got `i18n` exception on `ChatJoinRequest` 

### versions
```
aiogram 3.0.0b2 Modern and fully asynchronous framework for Telegram Bot API
├── aiofiles >=0.8.0,<0.9.0
├── aiohttp >=3.8.1,<4.0.0
│   ├── aiosignal >=1.1.2 
│   │   └── frozenlist >=1.1.0 
│   ├── async-timeout >=4.0.0a3,<5.0 
│   ├── attrs >=17.3.0 
│   ├── charset-normalizer >=2.0,<3.0 
│   ├── frozenlist >=1.1.1 (circular dependency aborted here)
│   ├── multidict >=4.5,<7.0 
│   └── yarl >=1.0,<2.0 
│       ├── idna >=2.0 
│       └── multidict >=4.0 (circular dependency aborted here)
├── babel >=2.9.1,<3.0.0
│   └── pytz >=2015.7 
├── magic-filter >=1.0.5,<2.0.0
├── pydantic >=1.9.0,<2.0.0
│   ├── python-dotenv >=0.10.4 
│   └── typing-extensions >=3.7.4.3 
└── pygments >=2.11.2,<3.0.0
```

## Expected Behavior

Correct language handling

## Current Behavior

```python
Traceback (most recent call last):
  File "aiogram/dispatcher/dispatcher.py", line 238, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "aiogram/dispatcher/dispatcher.py", line 104, in feed_update
    response = await self.update.wrap_outer_middleware(self.update.trigger, update, kwargs)
  File "aiogram/dispatcher/middlewares/error.py", line 28, in __call__
    response = await self.router.propagate_event(
  File "aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "aiogram/dispatcher/router.py", line 124, in _wrapped
    return await self._propagate_event(
  File "aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "aiogram/utils/i18n/middleware.py", line 66, in __call__
    current_locale = await self.get_locale(event=event, data=data) or self.i18n.default_locale
  File "aiogram/utils/i18n/middleware.py", line 128, in get_locale
    if locale.language not in self.i18n.available_locales:
AttributeError: 'NoneType' object has no attribute 'language'
```

**Comment by Olegt0rr** [comment]
It seems as also a Telegram bug, cause
`language_code=None`

**Comment by evgfilim1** [comment]
> It seems as also a Telegram bug, cause `language_code=None`

`language_code` is an optional field.
https://core.telegram.org/bots/api#user

**Comment by Olegt0rr** [comment]
I know that it's optional, so it's an aiogram bug too and should be fixed.
But I also ask Telegram API developer to fill `language_code`

**Comment by Olegt0rr** [comment]
@evgfilim1,

> Aliaksei Levin:
> The language code was supposed to be available in these updates. I've reported the issue.
