### ISSUE TITLE
Exeption if use dp.proccess_update() and /cmd@bot_name

### ISSUE THREAD

**Issue by SvineruS** [aiogram/aiogram#90]
---
name: Bug with proccess_update()
about: Exeption if use dp.proccess_update() and /cmd@bot_name

---

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10 x64
* Python Version: 3.7.1
* aiogram version: 2.0
* aiohttp version: 3.4.4
* uvloop version (if installed): 

## Failure Information (for bugs)
I use one server for several bots, so instead of the code from the examples I use `types.Update(**update)` and `dp.process_update()` for each bot and I catch this error when I use commands with the bot name. / start @ mybot does not work, / start works well

### Steps to Reproduce
just code
```python3
import asyncio
from aiogram import Bot, Dispatcher, types

API_TOKEN = '....'
bot = Bot(token=API_TOKEN)
dp = Dispatcher(bot)


@dp.message_handler(commands=['start', 'help'])
async def send_welcome(message: types.Message):
    await message.reply("Hi!\nI'm EchoBot!\nPowered by aiogram.")

async def myupdate():
    update = {"update_id": 957250703, "message": {"message_id": 12345, "from": {"id": 12345, "is_bot": False, "first_name": "qwerty", "last_name": "qwerty", "username": "qwerty", "language_code": "ru"}, "chat": {"id": -123456, "title": "qwerty", "username": "qwerty", "type": "supergroup"}, "date": 1544743937, "text": "/go@svinexample_bot", "entities": [{"offset": 0, "length": 19, "type": "bot_command"}]}}
    update = types.Update(**update)
    await dp.process_updates([update])


loop = asyncio.get_event_loop()
tasks = [loop.create_task(myupdate())]
wait_tasks = asyncio.wait(tasks)
loop.run_until_complete(wait_tasks)
loop.close()
```
### Failure Logs
```
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024BF17EC940>
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<myupdate() done, defined at C:/Users/Владислав/Desktop/test/mybot/my_bot.py:33> exception=AttributeError("'NoneType' object has no attribute 'me'")>
Traceback (most recent call last):
  File "C:/Users/Владислав/Desktop/test/mybot/my_bot.py", line 36, in myupdate
    await dp.process_updates([update])
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 147, in process_updates
    return await asyncio.gather(*tasks)
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\handler.py", line 99, in notify
    response = await handler(*args, **partial_data)
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 168, in process_update
    return await self.message_handlers.notify(update.message)
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\handler.py", line 90, in notify
    data.update(await check_filters(self.dispatcher, filters, args))
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 60, in check_filters
    f = await check_filter(dispatcher, filter_, args)
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 43, in check_filter
    return await filter_(*args, **kwargs)
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\filters\filters.py", line 144, in __call__
    return await self.check(obj)
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\filters\builtin.py", line 56, in check
    return await self.check_command(message, self.commands, self.prefixes, self.ignore_case, self.ignore_mention)
  File "D:\Programs\Python\lib\site-packages\aiogram\dispatcher\filters\builtin.py", line 63, in check_command
    if not ignore_mention and mention and (await message.bot.me).username.lower() != mention.lower():
AttributeError: 'NoneType' object has no attribute 'me'
```

**Comment by JrooTJunior** [comment]
This error causes because you dont set required context variables.
For e.g. executor has that lines what you need to add in your code before process update: 
https://github.com/aiogram/aiogram/blob/c029c337679574c520adef2ae840ddf218c33d95/aiogram/utils/executor.py#L144-L146

**Comment by JrooTJunior** [comment]
And also you can use `await dp.process_update(update)` instead of `await dp.process_updates([update])`

**Comment by Pyroarsonist** [comment]
**свин петух**
