### ISSUE TITLE
Message can't be edited with ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by MaslinDenis** [aiogram/aiogram#921]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows 11
* Python Version: 3.10.4
* aiogram version: 2.20
* aiohttp version: 3.8.1
* uvloop version (if installed): 

## Expected Behavior

The message with ReplyKeyboardMarkup keyboard will be edited

## Current Behavior

Error. The message has not been edited

## Failure Information (for bugs)

Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Dispatcher._process_polling_updates() done, defined at ...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=MessageCantBeEdited("Message can't be edited")>
Traceback (most recent call last):
  File "...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "...\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "...\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "...\commands\connect_commands.py", line 38, in join_command
    await bot.edit_message_text(output_string, chat_id=user.id, message_id=user.msg_users)
  File "...\venv\lib\site-packages\aiogram\bot\bot.py", line 2735, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
  File "D:\projects\planing_bot\venv\lib\site-packages\aiogram\bot\base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "...\venv\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "...\venv\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "...\venv\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageCantBeEdited: Message can't be edited

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. create bot
    storage = MemoryStorage()
    bot = Bot(os.getenv("BOT_TOKEN"))
    dispatcher = Dispatcher(bot, storage=storage)
2. send message with keyboard
    keyboard = types.ReplyKeyboardMarkup(resize_keyboard=True)
    keyboard.row(types.KeyboardButton('start'))
    await bot.send_message(text='test', chat_id=message.from_user.id, reply_markup=keyboard )
3. edit message
    await bot.edit_message_text('test2', chat_id=message.from_user.id, message_id=message.chat.id)
5. you get it...

### Failure Logs

Task exception was never retrieved
future: <Task finished name='Task-18' coro=<Dispatcher._process_polling_updates() done, defined at ...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=MessageCantBeEdited("Message can't be edited")>
Traceback (most recent call last):
  File "...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "...\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "...\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "...\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 116, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "...\commands\connect_commands.py", line 38, in join_command
    await bot.edit_message_text(output_string, chat_id=user.id, message_id=user.msg_users)
  File "...\venv\lib\site-packages\aiogram\bot\bot.py", line 2735, in edit_message_text
    result = await self.request(api.Methods.EDIT_MESSAGE_TEXT, payload)
  File "D:\projects\planing_bot\venv\lib\site-packages\aiogram\bot\base.py", line 231, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
  File "...\venv\lib\site-packages\aiogram\bot\api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "...\venv\lib\site-packages\aiogram\bot\api.py", line 115, in check_result
    exceptions.BadRequest.detect(description)
  File "...\venv\lib\site-packages\aiogram\utils\exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.MessageCantBeEdited: Message can't be edited

**Comment by JrooTJunior** [comment]
Messages with reply markup can't be edited as described in the Bot API Docs:

https://core.telegram.org/bots/api#updating-messages

> **Updating messages**
> Please note, that it is currently only possible to edit messages without reply_markup or with inline keyboards.

So, that's mean you can't do that and this issue is not in our (aiogram) side.
