### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by json1c** [aiogram/aiogram#959]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Context

- Operating system: Arch
- Python Version: 3.10.4
- aiogram version: 2.20
- aiohttp version: 3.8.1

Non-working example: https://raw.githubusercontent.com/aiogram/aiogram/dev-3.x/examples/multibot.py

### Expected behavior

normal work

### Current behavior

script not starting

### Steps to reproduce

start script

### Logs

```sh
Traceback:
1) `Traceback (most recent call last):
  File "/home/json1c/multibot.py", line 5, in <module>
    from finite_state_machine import form_router
ModuleNotFoundError: No module named 'finite_state_machine'`

after installing finite_state_machine getting this error:

`Traceback (most recent call last):
  File "/home/json1c/multibot.py", line 5, in <module>
    from finite_state_machine import form_router
ImportError: cannot import name 'form_router' from 'finite_state_machine' (/home/json1c/.local/lib/python3.10/site-packages/finite_state_machine/__init__.py)`
```

**Comment by json1c** [comment]
Oh, sorry😁
